import {env} from 'cloudflare:workers'
import {createExecutionContext,waitOnExecutionContext} from 'cloudflare:test'
import {it,expect} from 'vitest'
import worker from '../index'
async function call(path:string,cookie='',body?:unknown,scope='personal',method=body===undefined?'GET':'POST'){
 const ctx=createExecutionContext(),r=await worker.fetch(new Request('https://campus.test/api'+path,{method,headers:{cookie,origin:'https://campus.test','x-campus-request':'1','x-campus-scope':scope,'content-type':'application/json'},...(body===undefined?{}:{body:JSON.stringify(body)})}),env,ctx);await waitOnExecutionContext(ctx);return r
}
async function data(r:Response){const json=await r.json() as any;expect(json.ok,JSON.stringify(json)).toBe(true);return json.data}
async function user(login:string){const r=await call('/auth/register','',{login,password:'group-test-password-long'});expect(r.status,await r.clone().text()).toBe(201);const id=(await r.clone().json() as any).data.id;await env.DB.prepare('INSERT INTO account_permissions VALUES(?,?)').bind(id,JSON.stringify(['ai','groups','messengers','tasks'])).run();return r.headers.get('set-cookie')!.split(';')[0]}
it('isolates groups and subgroups, applies roles server-side, and keeps personal progress private',async()=>{
 const owner=await user('groupowner'),member=await user('groupmember'),outsider=await user('outsider')
 await data(await call('/groups',owner,{name:'Тестовая группа'}))
 const invitation=await data(await call('/groups/admin/invite',owner,{})),token=new URL(invitation.url).searchParams.get('invite')
 await data(await call('/groups/join',member,{token}))
 const g=await data(await call('/groups',owner)),me=(await data(await call('/groups',member))).members.find((m:any)=>m.role==='member')
 const sub=g.subgroups[0].id,other=g.subgroups[1].id
 expect((await call('/catalog/subjects',member,{name:'Запрещено',shortName:null,color:'#2563eb'},'common')).status).toBe(403)
 expect((await call('/schedule',outsider,undefined,'common')).status).toBe(403)
 expect((await call('/groups/admin/invite',member,{})).status).toBe(403)
 const course=await data(await call('/catalog/subjects',owner,{name:'Общий предмет',shortName:null,color:'#2563eb'},'common'))
 const slot=await data(await call('/catalog/slots',owner,{subjectId:course.id,teacherId:null,weekday:1,slotNumber:1,startTime:'09:00',endTime:'10:45',weekType:'both',lessonType:'Лекция',building:null,room:'420'},'common'))
 await data(await call('/groups/admin/members/'+me.id,owner,{role:'subhead',subgroupId:sub},'personal','PATCH'))
 expect((await data(await call('/schedule',member,undefined,'group'))).slots.some((s:any)=>s.id===slot.id)).toBe(true)
 expect((await call('/schedule',member,undefined,other)).status).toBe(403)
 expect((await call('/catalog/slots/'+slot.id+'/type',member,{lessonType:'Семинар'},'common','PATCH')).status).toBe(403)
 const homework=await data(await call('/homework',owner,{subjectId:course.id,title:'Общее задание'},'common'))
 await data(await call('/homework/'+homework.id,member,{status:'done'},'group','PATCH'))
 expect((await data(await call('/homework',member,undefined,'group'))).find((h:any)=>h.id===homework.id).status).toBe('done')
 expect((await data(await call('/homework',owner,undefined,'common'))).find((h:any)=>h.id===homework.id).status).toBe('open')
 for(const [path,method,body] of [['/homework/'+homework.id,'DELETE',undefined],['/materials/material-x','PATCH',{title:'x'}],['/materials/material-x','DELETE',undefined],['/attachments/attachment-x','DELETE',undefined]] as const)expect((await call(path,member,body,'common',method)).status).toBe(403)
 expect((await data(await call('/schedule',owner))).slots).toHaveLength(0)
 await data(await call('/groups/admin/invites',owner,undefined,'personal','DELETE'))
 expect((await call('/groups/join',outsider,{token})).status).toBe(410)
 expect((await call('/groups/leave',owner,{})).status).toBe(409)
})
it('publishes only the designated source schedule and imports into the shared workspace',async()=>{
 const owner=await user('sourceowner'),member=await user('sourcemember')
 await data(await call('/groups',owner,{name:'Группа источника'}))
 const invitation=await data(await call('/groups/admin/invite',owner,{}));await data(await call('/groups/join',member,{token:new URL(invitation.url).searchParams.get('invite')}))
 const empty={tables:[],links:[],error:null}
 const snapshot={capturedAt:new Date().toISOString(),semesterStart:'2026-09-01',semesterEnd:'2026-12-12',weeks:[2,3],lessons:[{subject:'Предмет источника',teacher:'Преподаватель',lessonType:'Лекция',building:null,room:'420',weekday:2,slotNumber:1,startTime:'09:00',endTime:'10:45',weekNumber:2}],grades:{...empty,tables:[{title:'ЛИЧНЫЕ ОЦЕНКИ',headers:['Оценка'],rows:[['95']]}]},umkd:empty}
 await data(await call('/connector/platonus/snapshot',owner,snapshot))
 await data(await call('/groups/schedule/source',owner,{},'common'))
 const preview=await data(await call('/groups/schedule/preview',owner,undefined,'common'))
 expect(JSON.stringify(preview)).not.toContain('ЛИЧНЫЕ ОЦЕНКИ')
 const row=preview.rows[0];await data(await call('/groups/schedule/import',owner,{snapshotId:preview.snapshot.id,index:row.index,revision:row.revision},'common'))
 expect((await data(await call('/schedule',member,undefined,'group'))).slots.some((s:any)=>s.subjectName==='Предмет источника')).toBe(true)
 expect((await call('/groups/schedule/source',member,{},'common')).status).toBe(403)
 expect((await data(await call('/platonus',member))).snapshot).toBeNull()
})
it('compares subgroup lessons without allowing writes and supports an absent common lesson',async()=>{
 const owner=await user('compareowner'),member=await user('comparemember')
 await data(await call('/groups',owner,{name:'Сравнение'}))
 const invite=await data(await call('/groups/admin/invite',owner,{}));await data(await call('/groups/join',member,{token:new URL(invite.url).searchParams.get('invite')}))
 const group=await data(await call('/groups',owner)),a=group.subgroups[0].id,b=group.subgroups[1].id
 const memberId=group.members.find((m:any)=>m.role==='member').id
 await data(await call('/groups/admin/members/'+memberId,owner,{role:'member',subgroupId:a},'personal','PATCH'))
 const course=await data(await call('/catalog/subjects',owner,{name:'Общая лекция',shortName:null,color:'#2563eb'},'common'))
 const slot=await data(await call('/catalog/slots',owner,{subjectId:course.id,teacherId:null,weekday:1,slotNumber:1,startTime:'09:00',endTime:'10:45',weekType:'both',lessonType:'Лекция',building:null,room:'420'},'common'))
 const subcourse=await data(await call('/catalog/subjects',owner,{name:'Семинар подгруппы',shortName:null,color:'#2563eb'},b))
 await data(await call('/catalog/slots',owner,{subjectId:subcourse.id,teacherId:null,weekday:1,slotNumber:1,startTime:'09:00',endTime:'10:45',weekType:'both',lessonType:'Семинар',building:null,room:'421'},b))
 const combined=await data(await call('/schedule/day?date=2026-09-14',owner,undefined,'all'))
 expect(combined.lessons).toHaveLength(2);expect(combined.lessons.every((l:any)=>l.audience.length===1)).toBe(true)
 expect((await call('/assistant',owner,{id:crypto.randomUUID(),text:'отмени'},'all')).status).toBe(403)
 expect((await call('/schedule/day?date=2026-09-14',member,undefined,'all')).status).toBe(403)
 expect((await call('/groups/exclusions',member,{slotId:slot.id,hidden:true},a)).status).toBe(403)
 await data(await call('/groups/exclusions',owner,{slotId:slot.id,hidden:true},a))
 expect((await data(await call('/schedule/day?date=2026-09-14',member,undefined,'group'))).lessons).toHaveLength(0)
 expect((await data(await call('/schedule/day?date=2026-09-14',owner,undefined,'common'))).lessons).toHaveLength(1)
 await data(await call('/groups/exclusions',owner,{slotId:slot.id,hidden:false},a))
 expect((await data(await call('/schedule/day?date=2026-09-14',member,undefined,'group'))).lessons).toHaveLength(1)
 const ownerId=group.members.find((m:any)=>m.role==='owner').id
 await data(await call('/groups/admin/members/'+ownerId+'/subgroup',owner,{subgroupId:a},'personal','PATCH'))
 const ownComparison=await data(await call('/schedule/day?date=2026-09-14',owner,undefined,'all'))
 expect(ownComparison.lessons.filter((l:any)=>l.isMine)).toHaveLength(1)
})
it('shares only UMKD from an authorized group source and revokes access after leaving',async()=>{
 const owner=await user('umkdowner'),member=await user('umkdmember'),outsider=await user('umkdoutsider')
 await data(await call('/groups',owner,{name:'Учебные материалы'}))
 const invite=await data(await call('/groups/admin/invite',owner,{}));await data(await call('/groups/join',member,{token:new URL(invite.url).searchParams.get('invite')}))
 const id=(await data(await call('/auth/me',owner))).id
 const snapshot={capturedAt:new Date().toISOString(),semesterStart:'2026-09-01',semesterEnd:'2026-12-12',weeks:[2,3],lessons:[],grades:{tables:[{title:'Личные оценки',headers:[],rows:[['95']]}],links:[],error:null},umkd:{tables:[],links:[{title:'Физика',url:'https://platonus.kstu.kz/v7/#/umkd/studentUmkd/42'}],error:null}}
 await env.WORKSPACES.get(env.WORKSPACES.idFromName(id)).fetch('https://workspace/api/connector/platonus/snapshot',{method:'POST',headers:{'x-campus-owner':id,'content-type':'application/json'},body:JSON.stringify(snapshot)})
 await data(await call('/groups/schedule/source',owner,{},'common'))
 const shared=await data(await call('/groups/umkd',member))
 expect(shared.section.links[0].title).toBe('Физика');expect(JSON.stringify(shared)).not.toContain('Личные оценки')
 expect((await call('/groups/umkd',outsider)).status).toBe(403)
 expect((await call('/groups/umkd/999/files',member)).status).toBe(422)
 expect((await data(await call('/platonus',member))).snapshot).toBeNull()
 await data(await call('/groups/leave',member,{}))
 expect((await call('/groups/umkd/42/files',member)).status).toBe(403)
})
it('deletes a confirmed subgroup, blocks assigned members, and preserves other schedules',async()=>{
 const owner=await user('deleteowner'),member=await user('deletemember'),outsider=await user('deleteoutsider')
 await data(await call('/groups',owner,{name:'Удаление подгруппы'}))
 const invite=await data(await call('/groups/admin/invite',owner,{}));await data(await call('/groups/join',member,{token:new URL(invite.url).searchParams.get('invite')}))
 const group=await data(await call('/groups',owner)),sub=group.subgroups[0],other=group.subgroups[1],memberId=group.members.find((m:any)=>m.role==='member').id
 const path='/groups/admin/subgroups/'+sub.id
 expect((await call(path,member,{name:sub.name},'personal','DELETE')).status).toBe(403)
 expect((await call(path,outsider,{name:sub.name},'personal','DELETE')).status).toBe(403)
 expect((await call(path,owner,{name:'wrong'},'personal','DELETE')).status).toBe(400)
 await data(await call('/groups/admin/members/'+memberId,owner,{role:'member',subgroupId:sub.id},'personal','PATCH'))
 expect((await call(path,owner,{name:sub.name},'personal','DELETE')).status).toBe(409)
 expect((await data(await call('/groups',owner))).subgroups).toHaveLength(2)
 await data(await call('/groups/admin/members/'+memberId,owner,{role:'member',subgroupId:other.id},'personal','PATCH'))
 await data(await call('/groups/subgroup-request',member,{id:sub.id}))
 const course=await data(await call('/catalog/subjects',owner,{name:'Удаляемый предмет',shortName:null,color:'#2563eb'},sub.id))
 await data(await call('/catalog/slots',owner,{subjectId:course.id,teacherId:null,weekday:1,slotNumber:1,startTime:'09:00',endTime:'10:45',weekType:'both',lessonType:null,building:null,room:null},sub.id))
 await env.DB.prepare('INSERT INTO group_sources(group_id,scope,account_id) VALUES(?,?,?)').bind(group.group.id,sub.id,group.members.find((m:any)=>m.role==='owner').id).run()
 await env.DB.prepare("INSERT INTO group_schedule_notices(group_id,scope,fingerprint,changed) VALUES(?,?,'test',1)").bind(group.group.id,sub.id).run()
 await data(await call(path,owner,{name:sub.name},'personal','DELETE'))
 const after=await data(await call('/groups',owner));expect(after.subgroups.map((s:any)=>s.id)).toEqual([other.id]);expect(after.members.find((m:any)=>m.id===memberId).requestedSubgroupId).toBeNull()
 expect((await call('/catalog',owner,undefined,sub.id)).status).toBe(403)
 expect((await call('/catalog',owner,undefined,other.id)).status).toBe(200)
 expect(await env.DB.prepare('SELECT * FROM group_sources WHERE scope=?').bind(sub.id).first()).toBeNull()
 expect(await env.DB.prepare('SELECT * FROM group_schedule_notices WHERE scope=?').bind(sub.id).first()).toBeNull()
 expect((await call(path,owner,{name:sub.name},'personal','DELETE')).status).toBe(404)
})
async function joined(owner:string,...others:string[]){const invite=await data(await call('/groups/admin/invite',owner,{}));for(const cookie of others)await data(await call('/groups/join',cookie,{token:invite.code}));return data(await call('/groups',owner))}
const idOf=(group:any,role:string)=>group.members.find((m:any)=>m.role===role).id
it('enforces role hierarchy for heads, members and the owner and cleans up removed members',async()=>{
 const owner=await user('roleowner'),head=await user('rolehead'),member=await user('rolemember'),other=await user('roleother')
 await data(await call('/groups',owner,{name:'Роли'}))
 let g=await joined(owner,head,member,other);const [sub]=g.subgroups,ownerId=idOf(g,'owner'),ids=g.members.filter((m:any)=>m.role==='member').map((m:any)=>m.id)
 const [headId,memberId,otherId]=await Promise.all([head,member,other].map(async cookie=>(await data(await call('/auth/me',cookie))).id))
 expect(ids.sort()).toEqual([headId,memberId,otherId].sort())
 await data(await call('/groups/admin/members/'+headId,owner,{role:'head',subgroupId:null},'personal','PATCH'))
 // Members cannot administer; heads cannot escalate, touch other heads or the owner.
 for(const [path,method,body] of [['/groups/admin/invite','POST',{}],['/groups/admin/members/'+otherId,'PATCH',{role:'head',subgroupId:null}],['/groups/admin/members/'+otherId,'DELETE',undefined],['/groups/admin/transfer/'+memberId,'POST',{}],['/groups/admin/group','PATCH',{name:'Взлом'}]] as const)expect((await call(path,member,body,'personal',method)).status).toBe(403)
 expect((await call('/groups/admin/members/'+memberId,head,{role:'head',subgroupId:null},'personal','PATCH')).status).toBe(403)
 expect((await call('/groups/admin/members/'+ownerId,head,{role:'member',subgroupId:null},'personal','PATCH')).status).toBe(403)
 expect((await call('/groups/admin/members/'+ownerId,owner,{role:'head',subgroupId:null},'personal','PATCH')).status).toBe(403)
 expect((await call('/groups/admin/members/'+ownerId+'/subgroup',head,{subgroupId:sub.id},'personal','PATCH')).status).toBe(403)
 expect((await call('/groups/admin/members/'+ownerId,head,undefined,'personal','DELETE')).status).toBe(403)
 expect((await call('/groups/admin/transfer/'+memberId,head,{})).status).toBe(403)
 expect((await call('/groups/admin/members/'+headId,head,undefined,'personal','DELETE')).status).toBe(400)
 expect((await call('/groups/admin/members/'+crypto.randomUUID(),head,undefined,'personal','DELETE')).status).toBe(404)
 // Subheads always keep a subgroup.
 expect((await call('/groups/admin/members/'+memberId,owner,{role:'subhead',subgroupId:null},'personal','PATCH')).status).toBe(400)
 await data(await call('/groups/admin/members/'+memberId,owner,{role:'subhead',subgroupId:sub.id},'personal','PATCH'))
 expect((await call('/groups/admin/members/'+memberId+'/subgroup',head,{subgroupId:null},'personal','PATCH')).status).toBe(400)
 await data(await call('/groups/admin/members/'+memberId,head,{role:'subhead',subgroupId:g.subgroups[1].id},'personal','PATCH'))
 // A removed member loses source assignments and private progress for the group.
 await env.DB.prepare('INSERT INTO group_sources(group_id,scope,account_id) VALUES(?,?,?)').bind(g.group.id,g.subgroups[1].id,memberId).run()
 await env.DB.prepare("INSERT INTO group_homework_progress(account_id,group_id,homework_id,status) VALUES(?,?,'hw','done')").bind(memberId,g.group.id).run()
 await data(await call('/groups/admin/members/'+memberId,head,undefined,'personal','DELETE'))
 expect(await env.DB.prepare('SELECT 1 FROM group_sources WHERE account_id=?').bind(memberId).first()).toBeNull()
 expect(await env.DB.prepare('SELECT 1 FROM group_homework_progress WHERE account_id=?').bind(memberId).first()).toBeNull()
 expect((await data(await call('/groups',member))).group).toBeNull()
 await data(await call('/groups/admin/group',head,{name:'Роли и права'},'personal','PATCH'))
 g=await data(await call('/groups',other));expect(g.group.name).toBe('Роли и права');expect(g.invites).toBeUndefined()
 expect((await data(await call('/groups',head))).invites.active).toBe(1)
})
it('normalizes invite tokens, regenerates links, rejects expired ones and handles double joins',async()=>{
 const owner=await user('inviteowner'),a=await user('invitea'),b=await user('inviteb'),c=await user('invitec')
 await data(await call('/groups',owner,{name:'Приглашения'}))
 const first=await data(await call('/groups/admin/invite',owner,{}))
 expect((await data(await call('/groups/invitation/'+first.code.toUpperCase(),a))).name).toBe('Приглашения')
 expect((await call('/groups/join',a,{token:'not-a-valid-invite-token!!'})).status).toBe(400)
 await data(await call('/groups/join',a,{token:`  ${first.url.replace(first.code,first.code.toUpperCase())} `}))
 expect((await call('/groups/join',a,{token:first.code})).status).toBe(409)
 const second=await data(await call('/groups/admin/invite',owner,{replace:true}))
 expect((await call('/groups/join',b,{token:first.code})).status).toBe(410)
 await data(await call('/groups/join',b,{token:second.code.toUpperCase()}))
 await env.DB.prepare('UPDATE group_invites SET expires_at=? WHERE token_hash IS NOT NULL AND revoked=0').bind(Date.now()-1).run()
 expect((await call('/groups/join',c,{token:second.code})).status).toBe(410)
 expect((await call('/groups/invitation/'+second.code,c)).status).toBe(410)
 await data(await call('/groups/admin/invite',owner,{}))
 expect((await env.DB.prepare('SELECT count(*) AS n FROM group_invites i JOIN study_groups g ON g.id=i.group_id WHERE g.name=?').bind('Приглашения').first<{n:number}>())!.n).toBe(1)
 expect((await call('/groups',c,{name:'Приглашения-2'})).status).toBe(201)
 expect((await call('/groups',c,{name:'Ещё одна'})).status).toBe(409)
 expect((await call('/groups/admin/subgroups',c,{name:'подгруппа 1'})).status).toBe(409)
})
it('transfers ownership atomically and lets the former owner leave',async()=>{
 const owner=await user('transferowner'),member=await user('transfermember'),outsider=await user('transferoutsider')
 await data(await call('/groups',owner,{name:'Передача'}))
 expect(((await (await call('/groups/leave',owner,{})).json()) as any).error.message).toContain('единственный')
 const g=await joined(owner,member),memberId=idOf(g,'member'),ownerId=idOf(g,'owner'),outsiderId=(await data(await call('/auth/me',outsider))).id
 expect((await call('/groups/admin/transfer/'+outsiderId,owner,{})).status).toBe(404)
 expect((await call('/groups/admin/transfer/'+ownerId,owner,{})).status).toBe(404)
 expect((await call('/groups/leave',owner,{})).status).toBe(409)
 await data(await call('/groups/admin/transfer/'+memberId,owner,{}))
 const after=await data(await call('/groups',member))
 expect(after.member.role).toBe('owner');expect(after.group.owner_id).toBe(memberId);expect(after.members.find((m:any)=>m.id===ownerId).role).toBe('head')
 expect((await call('/groups/admin/transfer/'+memberId,owner,{})).status).toBe(403)
 await data(await call('/groups/leave',owner,{}))
 expect((await call('/groups/leave',owner,{})).status).toBe(404)
 expect((await data(await call('/groups',member))).members).toHaveLength(1)
})
it('suggests the Platonus group without exposing other groups',async()=>{
 const student=await user('platonusstudent'),owner=await user('platonusowner')
 const [studentId,ownerId]=await Promise.all([student,owner].map(async cookie=>(await data(await call('/auth/me',cookie))).id))
 const profile=(id:string)=>env.DB.prepare("INSERT INTO account_profiles(account_id,platonus_group,connected,updated_at) VALUES(?,'ВТ-24-1',1,?) ON CONFLICT(account_id) DO UPDATE SET platonus_group=excluded.platonus_group").bind(id,Date.now()).run()
 await profile(studentId);await profile(ownerId)
 expect((await data(await call('/groups',student))).suggestion).toEqual({name:'ВТ-24-1',exists:false})
 await data(await call('/groups',owner,{name:'Наша группа'}))
 const seen=await data(await call('/groups',student));expect(seen.suggestion).toEqual({name:'ВТ-24-1',exists:true});expect(JSON.stringify(seen)).not.toContain('Наша группа')
 expect((await data(await call('/groups',owner))).platonusGroup).toBe('ВТ-24-1')
})
