import {AdminDrilldown} from './admin-drilldown'
import {useEffect,useMemo,useRef,useState} from 'react'
import {Activity,CalendarDays,Clock,Link2,TrendingUp,UserPlus,Users} from 'lucide-react'
import {requestApi} from '../lib/api-client'
import {Button} from './ui/button'

type EventRow={id:string;login:string;name?:string;kind:string;page:string;device:string;browser:string;detail:string|null;created_at:number}
type Daily={day:string;views:number;users:number;registrations:number}
type Stats={online:number;summary:{kind:string;count:number;users:number}[];pages:{page:string;count:number;users:number}[];devices:{device:string;browser:string;count:number}[];events:EventRow[];daily:Daily[]}
type TopUser={id:string;login:string;name:string;nameSource:'platonus'|'login'|'account';platonus_login:string|null;group:string|null;ms:number;events:number;days:number;lastSeenAt:number|null}
type Overview={days:number;totals:{users:number;newPeriod:number;newToday:number;new7:number;connected:number;withGroup:number};active:{online:number;dau:number;wau:number;mau:number;period:number};avgDailyMs:number|null;measuredMs:number;daily:{day:string;users:number;ms:number}[];heatmap:{dow:number;hour:number;views:number;users:number}[];groups:{name:string;users:number;connected:number;active:number}[];top:TopUser[];retention:{prevWeek:number;returnedWeek:number;periodUsers:number;multiDay:number;newUsers:number;newReturned:number}}
// Защита от неполного ответа (старый сервер, ошибка части запросов): страница не должна падать целиком.
function normalizeOverview(v:Partial<Overview>|null|undefined,days:number):Overview{const n=(x:unknown)=>typeof x==='number'&&Number.isFinite(x)?x:0,list=<T,>(x:T[]|undefined)=>Array.isArray(x)?x:[]
 const t=(v?.totals??{}) as Partial<Overview['totals']>,a=(v?.active??{}) as Partial<Overview['active']>,r=(v?.retention??{}) as Partial<Overview['retention']>
 return {days:n(v?.days)||days,totals:{users:n(t.users),newPeriod:n(t.newPeriod),newToday:n(t.newToday),new7:n(t.new7),connected:n(t.connected),withGroup:n(t.withGroup)},active:{online:n(a.online),dau:n(a.dau),wau:n(a.wau),mau:n(a.mau),period:n(a.period)},avgDailyMs:typeof v?.avgDailyMs==='number'?v.avgDailyMs:null,measuredMs:n(v?.measuredMs),daily:list(v?.daily),heatmap:list(v?.heatmap),groups:list(v?.groups),top:list(v?.top),retention:{prevWeek:n(r.prevWeek),returnedWeek:n(r.returnedWeek),periodUsers:n(r.periodUsers),multiDay:n(r.multiDay),newUsers:n(r.newUsers),newReturned:n(r.newReturned)}}}
const pages:Record<string,string>={schedule:'Расписание',assistant:'AI',library:'УМКД',grades:'Оценки',settings:'Настройки',admin:'Админка',auth:'Вход',tasks:'Задания',materials:'Материалы',history:'История',messages:'Сообщения',processing:'Обработка',people:'Люди',platonus:'Platonus',group:'Группа'}
const kinds:Record<string,string>={'page.view':'Открытия разделов','account.login':'Входы','account.register':'Регистрации','document.open':'Открытые документы','document.download':'Скачивания'}
const colors=['var(--viz-1)','var(--viz-2)','var(--viz-3)','var(--viz-4)']
const dayLabel=(value:string)=>new Date(value+'T00:00:00Z').toLocaleDateString('ru-RU',{day:'numeric',month:'short',timeZone:'UTC'})
const minutes=(ms:number|null)=>ms==null?'—':ms<60000?`${Math.round(ms/1000)} с`:ms<3600000?`${Math.round(ms/60000)} мин`:`${Math.floor(ms/3600000)} ч ${Math.round(ms/60000)%60} мин`
const pct=(part:number,whole:number)=>whole?`${Math.round(part/whole*100)}%`:'—'
const nice=(v:number)=>{if(v<=5)return Math.max(1,Math.ceil(v));const p=10**Math.floor(Math.log10(v)),m=v/p;return (m<=1?1:m<=2?2:m<=5?5:10)*p}
const card='min-w-0 rounded-xl border bg-card p-4'
const empty=(text:string)=><p className="py-12 text-center text-sm text-muted-foreground">{text}</p>

function fillDays(rows:Daily[],days:number){const map=new Map(rows.map(row=>[row.day,row]));return Array.from({length:days},(_,index)=>{const date=new Date(Date.now()+5*3600000);date.setUTCHours(0,0,0,0);date.setUTCDate(date.getUTCDate()-(days-index-1));const day=date.toISOString().slice(0,10);return map.get(day)??{day,views:0,users:0,registrations:0}})}

/** Charts draw in real pixels so axis text stays legible from 390px phones to wide desktops. */
function useWidth(){const ref=useRef<HTMLDivElement>(null),[width,setWidth]=useState(640);useEffect(()=>{const el=ref.current;if(!el)return;const observer=new ResizeObserver(([entry])=>setWidth(Math.max(260,Math.round(entry.contentRect.width))));observer.observe(el);return()=>observer.disconnect()},[]);return [ref,width] as const}

function Kpi({label,value,hint,Icon}:{label:string;value:string|number;hint?:string;Icon:typeof Users}){return <div className="min-w-0 rounded-xl border bg-card p-3"><div className="flex items-center gap-2 text-xs text-muted-foreground"><Icon className="size-4 text-primary"/><span className="truncate">{label}</span></div><strong className="mt-2 block text-2xl tabular-nums">{value}</strong>{hint&&<span className="block truncate text-xs text-muted-foreground">{hint}</span>}</div>}

/** Single-series area chart with crosshair tooltip; arrows move, Enter opens the day. */
function AreaChart({rows,title,note,onSelect,describe}:{rows:{day:string;value:number}[];title:string;note?:string;onSelect:(day:string)=>void;describe:(index:number)=>string}){
 const [hover,setHover]=useState<number|null>(null),ref=useRef<SVGSVGElement>(null),[box,W]=useWidth()
 const H=W<500?200:240,L=34,R=10,T=12,B=28,pw=W-L-R,ph=H-T-B,n=rows.length,step=pw/Math.max(1,n-1),max=nice(Math.max(0,...rows.map(r=>r.value)))
 const x=(i:number)=>L+i*step,y=(v:number)=>T+ph*(1-v/max),line=rows.map((r,i)=>`${i?'L':'M'}${x(i).toFixed(1)},${y(r.value).toFixed(1)}`).join('')
 const pick=(clientX:number)=>{const box=ref.current?.getBoundingClientRect();if(!box)return;setHover(Math.max(0,Math.min(n-1,Math.round(((clientX-box.left)/box.width*W-L)/step))))}
 const at=hover==null?null:rows[hover],left=hover==null?0:x(hover)/W*100
 return <figure className={card}><figcaption className="mb-2 flex flex-wrap items-baseline justify-between gap-2"><span className="text-sm font-semibold">{title}</span>{note&&<span className="text-xs text-muted-foreground">{note}</span>}</figcaption>
 <div ref={box}>{rows.some(r=>r.value)?<div className="relative">
  <svg ref={ref} viewBox={`0 0 ${W} ${H}`} className="h-auto w-full touch-pan-y cursor-pointer select-none outline-none" tabIndex={0} role="img" aria-label={`${title}. Стрелки — выбор дня, Enter — подробности`}
   onPointerMove={e=>pick(e.clientX)} onPointerDown={e=>pick(e.clientX)} onPointerLeave={e=>{if(e.pointerType==='mouse')setHover(null)}} onClick={()=>{if(at)onSelect(at.day)}}
   onFocus={()=>setHover(h=>h??n-1)} onBlur={()=>setHover(null)} onKeyDown={e=>{if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();setHover(h=>Math.max(0,Math.min(n-1,(h??n-1)+(e.key==='ArrowLeft'?-1:1))))}else if((e.key==='Enter'||e.key===' ')&&at){e.preventDefault();onSelect(at.day)}}}>
   {[0,.5,1].map(level=><g key={level}><line x1={L} x2={W-R} y1={T+ph*(1-level)} y2={T+ph*(1-level)} stroke="currentColor" strokeOpacity={level?.12:.3} className="text-foreground"/><text x={L-6} y={T+ph*(1-level)+4} textAnchor="end" fontSize="11" fill="currentColor" className="text-muted-foreground">{Math.round(max*level)}</text></g>)}
   <path d={`${line}L${x(n-1)},${T+ph}L${x(0)},${T+ph}Z`} style={{fill:'var(--viz-1)'}} fillOpacity=".14"/>
   <path d={line} fill="none" style={{stroke:'var(--viz-1)'}} strokeWidth="2" strokeLinejoin="round" strokeLinecap="round"/>
   {at&&<g><line x1={x(hover!)} x2={x(hover!)} y1={T} y2={T+ph} stroke="currentColor" strokeOpacity=".35" className="text-foreground"/><circle cx={x(hover!)} cy={y(at.value)} r="5" style={{fill:'var(--viz-1)'}} stroke="hsl(var(--card))" strokeWidth="2"/></g>}
   {[...new Set([0,Math.floor((n-1)/2),n-1])].map(i=><text key={i} x={x(i)} y={H-8} textAnchor={i===0?'start':i===n-1?'end':'middle'} fontSize="11" fill="currentColor" className="text-muted-foreground">{dayLabel(rows[i].day)}</text>)}
  </svg>
  {at&&<div role="status" className="pointer-events-none absolute top-0 z-10 max-w-[70%] rounded-lg border bg-card px-3 py-2 text-xs text-card-foreground shadow-md" style={{left:`${left}%`,transform:left<20?'none':left>80?'translateX(-100%)':'translateX(-50%)'}}><strong className="block">{dayLabel(at.day)}</strong>{describe(hover!)}<span className="mt-1 block text-muted-foreground">Нажмите — подробности дня</span></div>}
 </div>:empty('За этот период активности не было.')}</div></figure>
}

function DailyBars({rows,title,onSelect}:{rows:Daily[];title:string;onSelect:(day:string)=>void}){
 const [hover,setHover]=useState<number|null>(null),[box,W]=useWidth(),values=rows.map(r=>r.registrations),max=nice(Math.max(0,...values)),H=180,L=34,R=10,T=12,B=28,pw=W-L-R,ph=H-T-B,step=pw/Math.max(rows.length,1),bar=Math.max(2,Math.min(24,step-2))
 const at=hover==null?null:rows[hover],left=hover==null?0:(L+hover*step+step/2)/W*100
 return <figure className={card}><figcaption className="mb-2 flex justify-between gap-2 text-sm font-semibold"><span>{title}</span><span className="text-xs font-normal text-muted-foreground">всего {values.reduce((s,v)=>s+v,0)}</span></figcaption><div ref={box}>{values.some(Boolean)?<div className="relative"><svg viewBox={`0 0 ${W} ${H}`} className="h-auto w-full" role="group" aria-label={title} onPointerLeave={()=>setHover(null)}>
  {[0,1].map(level=><g key={level}><line x1={L} x2={W-R} y1={T+ph*(1-level)} y2={T+ph*(1-level)} stroke="currentColor" strokeOpacity={level?.12:.3} className="text-foreground"/><text x={L-6} y={T+ph*(1-level)+4} textAnchor="end" fontSize="11" fill="currentColor" className="text-muted-foreground">{Math.round(max*level)}</text></g>)}
  {rows.map((row,i)=>{const h=row.registrations/max*ph;return <g key={row.day} role="button" tabIndex={0} aria-label={`${dayLabel(row.day)}: ${row.registrations} регистраций. Подробнее`} className="cursor-pointer outline-none" onPointerEnter={()=>setHover(i)} onFocus={()=>setHover(i)} onBlur={()=>setHover(null)} onClick={()=>onSelect(row.day)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();onSelect(row.day)}}}><rect x={L+i*step} y={T} width={step} height={ph} fill="transparent"/>{h>0&&<path d={`M${L+i*step+(step-bar)/2},${T+ph}v${-Math.max(0,h-Math.min(4,h))}q0,${-Math.min(4,h)} ${Math.min(4,bar/2)},${-Math.min(4,h)}h${bar-2*Math.min(4,bar/2)}q${Math.min(4,bar/2)},0 ${Math.min(4,bar/2)},${Math.min(4,h)}v${Math.max(0,h-Math.min(4,h))}Z`} style={{fill:'var(--viz-3)'}} fillOpacity={hover===null||hover===i?1:.55}/>}</g>})}
  {[...new Set([0,Math.floor((rows.length-1)/2),rows.length-1])].map(i=><text key={i} x={L+i*step+step/2} y={H-8} textAnchor={i===0?'start':i===rows.length-1?'end':'middle'} fontSize="11" fill="currentColor" className="text-muted-foreground">{dayLabel(rows[i]?.day??'')}</text>)}
 </svg>{at&&<div role="status" className="pointer-events-none absolute top-0 z-10 rounded-lg border bg-card px-3 py-2 text-xs text-card-foreground shadow-md" style={{left:`${left}%`,transform:left<20?'none':left>80?'translateX(-100%)':'translateX(-50%)'}}><strong className="block">{dayLabel(at.day)}</strong>{at.registrations} новых аккаунтов</div>}</div>:empty('За этот период новых аккаунтов не было.')}</div></figure>
}

const weekdays=[[1,'Пн'],[2,'Вт'],[3,'Ср'],[4,'Чт'],[5,'Пт'],[6,'Сб'],[0,'Вс']] as const
function Heatmap({cells}:{cells:Overview['heatmap']}){
 const map=new Map(cells.map(c=>[`${c.dow}:${c.hour}`,c])),max=Math.max(0,...cells.map(c=>c.views)),[pick,setPick]=useState<{dow:number;hour:number}|null>(null)
 const peak=cells.reduce<Overview['heatmap'][number]|null>((best,c)=>!best||c.views>best.views?c:best,null),chosen=pick?map.get(`${pick.dow}:${pick.hour}`):null,name=(dow:number)=>weekdays.find(w=>w[0]===dow)?.[1]
 return <section className={card}><h3 className="text-sm font-semibold">Когда заходят · время Алматы</h3><p className="mb-3 text-xs text-muted-foreground">Открытия разделов по дням недели и часам{peak?` · пик: ${name(peak.dow)} ${peak.hour}:00`:''}</p>
 {max?<><div className="grid gap-[2px]" style={{gridTemplateColumns:'1.6rem repeat(24,minmax(0,1fr))'}} onPointerLeave={()=>setPick(null)}>
  {weekdays.map(([dow,label])=><div key={dow} className="contents"><span className="self-center text-[10px] text-muted-foreground">{label}</span>{Array.from({length:24},(_,hour)=>{const c=map.get(`${dow}:${hour}`),v=c?.views??0;return <button key={hour} type="button" aria-label={`${label} ${hour}:00 — ${v} открытий, ${c?.users??0} чел.`} onPointerEnter={()=>setPick({dow,hour})} onFocus={()=>setPick({dow,hour})} onClick={()=>setPick({dow,hour})} className={`aspect-square min-w-0 rounded-[3px] ${v?'':'bg-muted'} ${pick?.dow===dow&&pick.hour===hour?'ring-2 ring-foreground':''}`} style={v?{backgroundColor:`color-mix(in srgb, var(--viz-1) ${Math.round(18+82*v/max)}%, transparent)`}:undefined}/>})}</div>)}
  <span/>{Array.from({length:24},(_,h)=><span key={h} className="text-center text-[9px] text-muted-foreground">{h%6===0?h:''}</span>)}
 </div>
 <div className="mt-3 flex flex-wrap items-center justify-between gap-2 text-xs text-muted-foreground"><span aria-live="polite">{pick?`${name(pick.dow)} ${String(pick.hour).padStart(2,'0')}:00 — ${chosen?.views??0} открытий · ${chosen?.users??0} чел.`:'Наведите или нажмите на клетку'}</span><span className="flex items-center gap-1">меньше<i className="h-2 w-16 rounded-full" style={{background:'linear-gradient(90deg,color-mix(in srgb, var(--viz-1) 18%, transparent),var(--viz-1))'}}/>больше</span></div></>:empty('Открытий разделов за период нет.')}</section>
}

function Bars({title,rows,emptyText,footer}:{title:string;rows:{key:string;label:string;value:number;meta:string}[];emptyText:string;footer?:string}){const max=Math.max(1,...rows.map(r=>r.value));return <section className={card}><h3 className="text-sm font-semibold">{title}</h3><div className="mt-4 space-y-3">{rows.map(row=><div key={row.key}><div className="mb-1 flex justify-between gap-3 text-xs"><span className="truncate">{row.label}</span><span className="shrink-0 tabular-nums text-muted-foreground">{row.meta}</span></div><div className="h-2 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full" style={{width:`${Math.max(2,row.value/max*100)}%`,backgroundColor:'var(--viz-1)'}}/></div></div>)}{!rows.length&&empty(emptyText)}</div>{footer&&<p className="mt-3 text-xs text-muted-foreground">{footer}</p>}</section>}

function DeviceChart({rows}:{rows:Stats['devices']}){
 const devices=useMemo(()=>{const totals=new Map<string,number>();for(const row of rows)totals.set(row.device,(totals.get(row.device)??0)+Number(row.count));return [...totals.entries()].sort((a,b)=>a[0].localeCompare(b[0]))},[rows]),browsers=useMemo(()=>{const totals=new Map<string,number>();for(const row of rows)totals.set(row.browser,(totals.get(row.browser)??0)+Number(row.count));return [...totals.entries()].sort((a,b)=>b[1]-a[1]).slice(0,4)},[rows]),total=devices.reduce((sum,row)=>sum+row[1],0),radius=46,circumference=2*Math.PI*radius;let offset=0
 const names:Record<string,string>={phone:'Телефон',tablet:'Планшет',desktop:'Компьютер'},order=['desktop','phone','tablet'],color=(name:string)=>colors[Math.max(0,order.indexOf(name))%colors.length]
 return <section className={card}><h3 className="text-sm font-semibold">Устройства</h3>{total?<div className="mt-3 flex flex-col items-center gap-4 sm:flex-row"><svg viewBox="0 0 120 120" className="size-36 shrink-0" role="img" aria-label="Распределение устройств"><circle cx="60" cy="60" r={radius} fill="none" stroke="currentColor" strokeWidth="14" className="text-muted"/>{devices.map(([name,count])=>{const length=count/total*circumference,current=offset;offset+=length;return <circle key={name} cx="60" cy="60" r={radius} fill="none" style={{stroke:color(name)}} strokeWidth="14" strokeDasharray={`${Math.max(0,length-(devices.length>1?1.5:0))} ${circumference-length+(devices.length>1?1.5:0)}`} strokeDashoffset={-current} transform="rotate(-90 60 60)"><title>{names[name]??name}: {count}</title></circle>})}<text x="60" y="58" textAnchor="middle" fontSize="18" fontWeight="700" fill="currentColor">{total}</text><text x="60" y="73" textAnchor="middle" fontSize="9" fill="currentColor" className="text-muted-foreground">открытий</text></svg><div className="w-full space-y-2">{devices.map(([name,count])=><p key={name} className="flex items-center justify-between gap-3 text-sm"><span className="flex items-center gap-2"><i className="size-2.5 rounded-full" style={{backgroundColor:color(name)}}/>{names[name]??name}</span><span className="tabular-nums"><strong>{pct(count,total)}</strong> <span className="text-xs text-muted-foreground">{count}</span></span></p>)}<p className="border-t pt-2 text-xs text-muted-foreground">Браузеры: {browsers.map(([b,c])=>`${b} ${pct(c,total)}`).join(' · ')}</p></div></div>:empty('Данных об устройствах пока нет.')}</section>
}

function Meter({label,part,whole,hint}:{label:string;part:number;whole:number;hint:string}){return <div><div className="flex items-baseline justify-between gap-3 text-sm"><span>{label}</span><strong className="tabular-nums">{pct(part,whole)}</strong></div><div className="mt-1 h-2 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full" style={{width:whole?`${part/whole*100}%`:0,backgroundColor:'var(--viz-3)'}}/></div><p className="mt-1 text-xs text-muted-foreground">{whole?`${part} из ${hint}`:'Пока недостаточно данных'}</p></div>}

function TopUsers({rows,onSelect}:{rows:TopUser[];onSelect?:(id:string)=>void}){return <section className={`${card} lg:col-span-2`}><h3 className="text-sm font-semibold">Самые активные студенты</h3><p className="mb-3 text-xs text-muted-foreground">По времени с открытой вкладкой за период. Нажмите на имя — аналитика этого студента.</p>{rows.length?<div className="-mx-4 overflow-x-auto px-4"><table className="w-full min-w-[520px] text-left text-sm"><thead className="text-xs text-muted-foreground"><tr><th className="py-2 pr-3 font-medium">#</th><th className="py-2 pr-3 font-medium">Студент</th><th className="py-2 pr-3 font-medium">Группа</th><th className="py-2 pr-3 text-right font-medium">Время</th><th className="py-2 pr-3 text-right font-medium">Дней</th><th className="py-2 text-right font-medium">Последний визит</th></tr></thead><tbody>{rows.map((row,i)=><tr key={row.id} className="border-t"><td className="py-2 pr-3 tabular-nums text-muted-foreground">{i+1}</td><td className="py-2 pr-3"><button type="button" disabled={!onSelect} className="text-left hover:underline disabled:no-underline" onClick={()=>onSelect?.(row.id)}><span className="font-medium">{row.name}</span>{row.nameSource==='login'&&<span className="ml-1 rounded bg-muted px-1 text-[10px] text-muted-foreground" title="Имя получено из логина Platonus">по логину</span>}<span className="block text-xs text-muted-foreground">@{row.login}{row.platonus_login?` · Platonus: ${row.platonus_login}`:''}</span></button></td><td className="py-2 pr-3 text-xs">{row.group||'—'}</td><td className="py-2 pr-3 text-right tabular-nums">{minutes(row.ms)}</td><td className="py-2 pr-3 text-right tabular-nums">{row.days}</td><td className="whitespace-nowrap py-2 text-right text-xs text-muted-foreground">{row.lastSeenAt?new Date(row.lastSeenAt).toLocaleString('ru-RU',{timeZone:'Asia/Almaty',day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'}):'—'}</td></tr>)}</tbody></table></div>:empty('За период активности не было.')}</section>}

export function AdminAnalytics({accountId='',onClear,onSelectAccount}:{accountId?:string;onClear:()=>void;onSelectAccount?:(id:string)=>void}){
 const [selectedDay,setSelectedDay]=useState<string|null>(null)
 const [data,setData]=useState<Stats|null>(null),[overview,setOverview]=useState<Overview|null>(null),[days,setDays]=useState(30),[offset,setOffset]=useState(0),[error,setError]=useState(''),[version,setVersion]=useState(0),[busy,setBusy]=useState(false)
 useEffect(()=>{setOffset(0)},[accountId,days])
 useEffect(()=>{let active=true;setError('');void requestApi<Stats>(`/api/admin/analytics?days=${days}&account=${encodeURIComponent(accountId)}&offset=${offset}`).then(value=>{if(active)setData(value)}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[days,offset,accountId,version])
 useEffect(()=>{let active=true;setBusy(true);void requestApi<Overview>(`/api/admin/analytics/overview?days=${days}&account=${encodeURIComponent(accountId)}`).then(value=>{if(active)setOverview(normalizeOverview(value,days))}).catch(e=>{if(active)setError(e.message)}).finally(()=>{if(active)setBusy(false)});return()=>{active=false}},[days,accountId,version])
 const daily=useMemo(()=>fillDays(data?.daily??[],days),[data?.daily,days]),summary=new Map(data?.summary.map(item=>[item.kind,item])??[])
 const views=summary.get('page.view')?.count??0,docs=(summary.get('document.open')?.count??0)+(summary.get('document.download')?.count??0)
 const activeRows=useMemo(()=>(overview?.daily??[]).map(r=>({day:r.day,value:r.users})),[overview?.daily])
 const o=overview,tot=o?.totals,act=o?.active,ret=o?.retention
 return <section className="space-y-4">{selectedDay&&<AdminDrilldown day={selectedDay} accountId={accountId} onClose={()=>setSelectedDay(null)}/>}
 <div className="flex flex-wrap items-center gap-2"><div className="min-w-0 basis-full sm:basis-auto sm:flex-1"><h2 className="font-semibold">Аналитика</h2><p className="text-xs text-muted-foreground">{accountId?'Показан выбранный студент':'Все студенты'} · время Алматы{busy?' · обновляем…':''}</p></div>
  <div role="group" aria-label="Период статистики" className="flex rounded-lg border p-0.5">{[7,30,90].map(n=><button key={n} type="button" aria-pressed={days===n} onClick={()=>setDays(n)} className={`rounded-md px-3 py-1.5 text-xs font-medium ${days===n?'bg-primary text-primary-foreground':'text-muted-foreground hover:text-foreground'}`}>{n} дн.</button>)}</div>
  <label className="flex items-center gap-1 rounded-lg border px-2 text-xs text-muted-foreground"><CalendarDays className="size-4"/><span className="sr-only">Посещения за выбранный день</span><input type="date" className="bg-transparent py-1.5 text-sm text-foreground" max={new Date(Date.now()+5*3600000).toISOString().slice(0,10)} onChange={e=>{if(e.target.value)setSelectedDay(e.target.value)}}/></label>
  <Button variant="outline" size="sm" onClick={()=>setVersion(n=>n+1)}>Обновить</Button></div>
 {accountId&&<div className="flex flex-wrap items-center justify-between gap-2 rounded-xl bg-primary/5 p-3 text-sm"><span>Фильтр: один студент</span><Button size="sm" variant="outline" onClick={onClear}>Показать всех</Button></div>}
 {error&&<p role="alert" className="text-sm text-destructive">{error}</p>}
 {!o&&!data&&!error&&<p role="status" className="text-sm text-muted-foreground">Загружаем аналитику…</p>}
 {o&&tot&&act&&(accountId?<div className="grid grid-cols-2 gap-3 sm:grid-cols-4"><Kpi Icon={Activity} label="Сейчас в сети" value={act.online?'Да':'Нет'}/><Kpi Icon={CalendarDays} label="Активных дней" value={o.daily.filter(d=>d.users).length} hint={`из ${days}`}/><Kpi Icon={Clock} label="Время на сайте" value={minutes(o.measuredMs)} hint="за период, видимая вкладка"/><Kpi Icon={TrendingUp} label="Открытия разделов" value={views} hint={`документов: ${docs}`}/></div>
 :<div className="grid grid-cols-2 gap-3 sm:grid-cols-4">
  <Kpi Icon={Users} label="Всего студентов" value={tot.users} hint={`+${tot.newPeriod} за ${days} дн.`}/>
  <Kpi Icon={Activity} label="Сейчас в сети" value={act.online} hint="за последние 90 с"/>
  <Kpi Icon={TrendingUp} label="Активны сегодня · DAU" value={act.dau} hint={`${pct(act.dau,tot.users)} от всех`}/>
  <Kpi Icon={TrendingUp} label="За 7 дней · WAU" value={act.wau} hint={`${pct(act.wau,tot.users)} от всех`}/>
  <Kpi Icon={TrendingUp} label="За 30 дней · MAU" value={act.mau} hint={`DAU/MAU ${pct(act.dau,act.mau)}`}/>
  <Kpi Icon={UserPlus} label="Новые аккаунты" value={tot.newPeriod} hint={`сегодня ${tot.newToday} · 7 дн. ${tot.new7}`}/>
  <Kpi Icon={Link2} label="Platonus подключён" value={tot.connected} hint={`${pct(tot.connected,tot.users)} · с группой ${tot.withGroup}`}/>
  <Kpi Icon={Clock} label="Среднее время в день" value={minutes(o.avgDailyMs)} hint="на активного студента"/>
 </div>)}
 {o&&<div className="grid grid-cols-[minmax(0,1fr)] gap-4 lg:grid-cols-[repeat(2,minmax(0,1fr))]">
  <div className="min-w-0 lg:col-span-2"><AreaChart rows={activeRows} title={accountId?'Активность по дням':'Активные студенты по дням'} note={accountId?undefined:`в среднем ${activeRows.length?Math.round(activeRows.reduce((s,r)=>s+r.value,0)/activeRows.length*10)/10:0} в день`} onSelect={setSelectedDay} describe={i=>{const r=o.daily[i];return accountId?`${r.users?'Был на сайте':'Не заходил'} · ${minutes(r.ms)} на сайте`:`${r.users} активных · ${minutes(r.ms)} на сайте суммарно`}}/></div>
  {!accountId&&data&&<DailyBars rows={daily} title="Новые регистрации" onSelect={setSelectedDay}/>}
  {!accountId&&ret&&<section className={card}><h3 className="text-sm font-semibold">Возвращаемость</h3><div className="mt-4 space-y-4"><Meter label="Вернулись с прошлой недели" part={ret.returnedWeek} whole={ret.prevWeek} hint={`${ret.prevWeek} активных 8–14 дней назад`}/><Meter label="Заходили 2+ разных дня" part={ret.multiDay} whole={ret.periodUsers} hint={`${ret.periodUsers} активных за ${days} дн.`}/><Meter label="Новые вернулись после дня регистрации" part={ret.newReturned} whole={ret.newUsers} hint={`${ret.newUsers} новых за ${days} дн.`}/></div></section>}
  <Heatmap cells={o.heatmap}/>
  {data&&<DeviceChart rows={data.devices}/>}
  {data&&<Bars title="Какие разделы используют" emptyText="За этот период разделы не открывали." rows={data.pages.slice(0,8).map(r=>({key:r.page,label:pages[r.page]??r.page,value:Number(r.count),meta:`${r.count} · ${r.users} чел.`}))} footer={`Всего открытий: ${views} · документы УМКД: ${summary.get('document.open')?.count??0} открыто, ${summary.get('document.download')?.count??0} скачано · входов: ${summary.get('account.login')?.count??0}`}/>}
  {!accountId&&<Bars title="Учебные группы" emptyText="Группы появятся после подключения Platonus." rows={o.groups.map(g=>({key:g.name||'-',label:g.name||'Без группы',value:g.users,meta:`${g.users} чел. · ${g.active} акт. · ${g.connected} Platonus`}))} footer="Топ-12 по числу студентов. «акт.» — заходили за 7 дней."/>}
  {!accountId&&<TopUsers rows={o.top} onSelect={onSelectAccount}/>}
 </div>}
 {data&&<details className={card}><summary className="cursor-pointer text-sm font-medium">Подробный журнал событий</summary><div className="mt-3 max-h-96 overflow-auto rounded-lg border"><table className="w-full text-left text-xs"><caption className="p-3 text-left">{accountId?'Выбранный студент':'Все студенты'}</caption><thead><tr>{['Когда','Кто','Действие','Раздел / файл','Устройство'].map(label=><th key={label} className="p-2">{label}</th>)}</tr></thead><tbody>{data.events.map(event=><tr key={event.id} className="border-t"><td className="whitespace-nowrap p-2">{new Date(event.created_at).toLocaleString()}</td><td className="p-2">{event.name??event.login}<span className="block text-muted-foreground">@{event.login}</span></td><td className="p-2">{kinds[event.kind]??event.kind}</td><td className="p-2">{pages[event.page]??event.page}{event.detail?` · ${event.detail}`:''}</td><td className="p-2">{event.device} · {event.browser}</td></tr>)}</tbody></table>{!data.events.length&&<p className="p-3 text-sm text-muted-foreground">За этот период событий нет.</p>}</div><div className="mt-3 flex justify-between"><Button variant="outline" disabled={!offset} onClick={()=>setOffset(value=>Math.max(0,value-50))}>Назад</Button><Button variant="outline" disabled={data.events.length<50} onClick={()=>setOffset(value=>value+50)}>Далее</Button></div></details>}
 <p className="text-xs text-muted-foreground">Активность — открытия разделов, замеры видимой вкладки и последний сигнал присутствия. Подробные события хранятся 90 дней; время до начала замеров не учитывается.</p>
 </section>
}
