import {useEffect,useState} from 'react'
import {requestApi} from '../lib/api-client'
import {Modal} from './ui/modal'
import {Button} from './ui/button'
const labels:Record<string,string>={schedule:'Расписание',library:'УМКД',grades:'Оценки',settings:'Настройки',assistant:'AI',auth:'Вход',admin:'Админка'}
const actions:Record<string,string>={'page.view':'Открыл раздел','account.login':'Вошёл','account.register':'Зарегистрировался','document.open':'Открыл документ','document.download':'Скачал документ'}
type Detail={users:{account_id:string;login:string;name:string;firstAt:number;lastAt:number;visibleMs:number|null;events:number;pages:string}[];hourly:{hour:string;views:number;users:number}[];events:{id:string;login:string;name?:string;created_at:number;page:string;kind:string;detail?:string;device:string;browser:string}[]}
const time=(at:number)=>new Date(at).toLocaleTimeString('ru-RU',{timeZone:'Asia/Almaty',hour:'2-digit',minute:'2-digit'})
export function AdminDrilldown({day,accountId,onClose}:{day:string;accountId:string;onClose:()=>void}){
 const [data,setData]=useState<Detail|null>(null),[hour,setHour]=useState<number|null>(null),[user,setUser]=useState(accountId),[offset,setOffset]=useState(0),[error,setError]=useState(''),[busy,setBusy]=useState(true)
 const start=Date.parse(`${day}T00:00:00+05:00`),from=start+(hour??0)*3600000,to=hour===null?start+86400000:from+3600000
 useEffect(()=>{let active=true;setBusy(true);setError('');void requestApi<Detail>(`/api/admin/analytics/detail?from=${from}&to=${to}&account=${encodeURIComponent(user)}&offset=${offset}`).then(v=>{if(active)setData(v)}).catch(e=>{if(active)setError(e.message)}).finally(()=>{if(active)setBusy(false)});return()=>{active=false}},[from,to,user,offset])
 return <Modal wide title={`Посещения · ${new Date(start).toLocaleDateString('ru-RU',{timeZone:'Asia/Almaty'})}`} onClose={onClose}><div className="space-y-4">
 <div className="flex flex-wrap items-center gap-3"><span className="text-xs text-muted-foreground">Время Алматы</span><label className="text-sm">Час <select className="rounded-lg border bg-background p-2" value={hour??''} onChange={e=>{setHour(e.target.value===''?null:Number(e.target.value));setOffset(0)}}><option value="">Весь день</option>{Array.from({length:24},(_,h)=><option key={h} value={h}>{String(h).padStart(2,'0')}:00–{h+1}:00</option>)}</select></label>{user!==accountId&&<Button variant="outline" onClick={()=>{setUser(accountId);setOffset(0)}}>Все пользователи</Button>}</div>
 {error&&<p role="alert" className="text-destructive">{error}</p>}{busy&&<p role="status" className="text-sm">Загрузка…</p>}
 {data&&!busy&&<>
 {hour===null&&<div className="rounded-xl border p-3"><p className="mb-3 text-sm font-medium">Открытия разделов по часам</p><div className="flex h-28 items-end gap-1">{Array.from({length:24},(_,h)=>{const row=data.hourly.find(r=>Number(r.hour)===h),max=Math.max(1,...data.hourly.map(r=>r.views));return <button key={h} title={`${h}:00 · ${row?.views??0} открытий · ${row?.users??0} пользователей`} aria-label={`${h}:00, ${row?.views??0} открытий. Посмотреть посещения`} onClick={()=>{setHour(h);setOffset(0)}} className="group flex h-full min-w-0 flex-1 flex-col justify-end gap-1 rounded focus-visible:outline focus-visible:outline-2 focus-visible:outline-primary"><span className="min-h-2 rounded-t bg-blue-500 group-hover:bg-blue-400" style={{height:`${Math.max(5,(row?.views??0)/max*80)}%`}}/><span className="text-[9px] text-muted-foreground">{h%3===0?h:''}</span></button>})}</div></div>}
 <div className="overflow-x-auto rounded-xl border"><table className="w-full text-left text-sm"><thead className="bg-muted"><tr>{['Пользователь','Первая / последняя активность','Время на сайте','Разделы'].map(label=><th key={label} className="p-3 font-medium">{label}</th>)}</tr></thead><tbody>{data.users.map(row=><tr key={row.account_id} className="border-t"><td className="p-3"><button className="text-left text-primary hover:underline" onClick={()=>{setUser(row.account_id);setOffset(0)}}>{row.name}<span className="block text-xs text-muted-foreground">@{row.login}</span></button></td><td className="whitespace-nowrap p-3 text-xs">{time(row.firstAt)} — {time(row.lastAt)}</td><td className="whitespace-nowrap p-3">{row.visibleMs===null?'Нет замера':`${Math.floor(row.visibleMs/60000)} мин ${Math.floor(row.visibleMs/1000)%60} с`}</td><td className="p-3 text-xs">{row.pages.split(',').map(p=>labels[p]??p).join(', ')}</td></tr>)}</tbody></table>{!data.users.length&&<p className="p-4 text-sm text-muted-foreground">Посещений не было.</p>}</div>
 <div className="flex justify-between"><Button variant="outline" disabled={!offset} onClick={()=>setOffset(v=>v-30)}>Назад</Button><Button variant="outline" disabled={data.users.length<30} onClick={()=>setOffset(v=>v+30)}>Далее</Button></div>
 <p className="text-xs text-muted-foreground">Время — только при открытой вкладке. Замеры по дням доступны с этого обновления.</p>
 <h3 className="text-sm font-semibold">Последние события за выбранный период</h3><ol className="max-h-72 space-y-2 overflow-y-auto">{data.events.map(e=><li key={e.id} className="rounded-lg bg-muted/50 p-3 text-xs"><span className="font-medium">{time(e.created_at)} · {e.name??e.login}{e.name&&<span className="font-normal text-muted-foreground"> @{e.login}</span>}</span><p className="mt-1">{actions[e.kind]??e.kind} · {labels[e.page]??e.page}{e.detail&&` · ${e.detail}`}</p><span className="text-muted-foreground">{e.device} · {e.browser}</span></li>)}</ol>
 </>}
 </div></Modal>
}
