import {t,useLanguage} from '../lib/language'
import { LessonTypeField } from './lesson-type-field'
import { useEffect, useState } from 'react'
import { requestApi } from '../lib/api-client'
import { Button } from './ui/button'
import { LoadingState } from './ui/page-state'
type Row={id:string;[key:string]:string|number|null}
type Catalog={subjects:Row[];teachers:Row[];slots:Row[]}
type Kind=keyof Catalog
const field='mt-1 w-full min-w-0 rounded-md border bg-background px-3 py-2 text-sm'
const days=['Понедельник','Вторник','Среда','Четверг','Пятница','Суббота','Воскресенье']
const slotDefaults={subjectId:'',teacherId:null,weekday:1,slotNumber:1,startTime:'09:00',endTime:'10:45',weekType:'both',lessonType:null,building:null,room:null}
const defaults={subjects:{name:'',shortName:'',color:'#2563eb'},teachers:{name:'',email:null},slots:slotDefaults}
export function CatalogSettings({initialKind='teachers'}:{initialKind?:Kind}={}){
 useLanguage();
 const [data,setData]=useState<Catalog|null>(null),[kind,setKind]=useState<Kind>(initialKind),[editing,setEditing]=useState<Row|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false)
 const load=()=>requestApi<Catalog>('/api/catalog').then(setData)
 useEffect(()=>{void load().catch(e=>setError(e.message))},[])
 const change=(key:string,value:string|number|null)=>setEditing(e=>e?{...e,[key]:value}:null)
 async function save(){if(!editing)return;setBusy(true);setError('');setNotice('');try{const body=Object.fromEntries(Object.keys(defaults[kind]).map(key=>[key,editing[key]??null]));await requestApi(`/api/catalog/${kind}${editing.id?`/${editing.id}`:''}`,{method:editing.id?'PATCH':'POST',body:JSON.stringify(body)});await load();setEditing(null);setNotice(t("Сохранено в выбранном расписании."))}catch(e){setError(e instanceof Error?e.message:t("Ошибка сохранения"))}finally{setBusy(false)}}
 function select(key:string,label:string,options:{value:string|number;label:string}[]){return <label className="min-w-0 text-sm">{label}<select className={field} value={editing?.[key]??''} onChange={e=>change(key,['weekday','slotNumber'].includes(key)?Number(e.target.value):e.target.value||null)}>{options.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select></label>}
 function input(key:string,label:string,type='text'){return <label className="min-w-0 text-sm">{label}<input type={type} maxLength={key==='shortName'?60:200} required={['name','startTime','endTime'].includes(key)} className={field} value={editing?.[key]??''} onChange={e=>change(key,e.target.value)}/></label>}
 return <section className="space-y-4"><h2 className="text-base font-semibold">{t("Предметы, преподаватели и занятия")}</h2><p className="text-sm text-muted-foreground">{t("Исправьте имя преподавателя один раз — оно обновится у его занятий в выбранном расписании. Кабинет и корпус редактируются у конкретного занятия.")}</p><div className="flex flex-wrap gap-2">{(['teachers','subjects','slots'] as Kind[]).map(k=><Button key={k} variant={kind===k?'default':'outline'} disabled={busy} onClick={()=>{setKind(k);setEditing(null);setError('');setNotice('')}}>{{teachers:'Преподаватели',subjects:'Предметы',slots:'Занятия'}[k]}</Button>)}</div>
 {error&&<p role="alert" className="text-sm text-destructive">{error}</p>}{notice&&<p role="status" className="text-sm">{notice}</p>}{!data&&!error&&<LoadingState/>}
 {editing&&data?<form onSubmit={e=>{e.preventDefault();void save()}} className="space-y-4 rounded-lg border bg-card p-4"><h3 className="text-sm font-semibold">{editing.id?t("Редактирование"):t("Новая запись")}</h3><fieldset disabled={busy} className="grid min-w-0 gap-3 sm:grid-cols-2">{kind!=='slots'?<>{input('name',kind==='teachers'?t("Имя преподавателя"):t("Название предмета"))}{kind==='subjects'?<>{input('shortName',t("Короткое название"))}{input('color',t("Цвет"),'color')}</>:input('email',t("Email (необязательно)"),'email')}</>:<>{select('subjectId',t("Предмет"),[{value:'',label:'Выберите предмет'},...data.subjects.map(r=>({value:r.id,label:String(r.name)}))])}{select('teacherId',t("Преподаватель"),[{value:'',label:'Не указан'},...data.teachers.map(r=>({value:r.id,label:String(r.name)}))])}{select('weekday',t("День"),days.map((label,i)=>({value:i+1,label})))}{select('weekType',t("Неделя"),[{value:'odd',label:'Числитель'},{value:'even',label:'Знаменатель'},{value:'both',label:'Каждая'}])}{select('slotNumber',t("Номер пары"),Array.from({length:10},(_,i)=>({value:i+1,label:String(i+1)})))}{<LessonTypeField value={String(editing.lessonType??'')} onChange={value=>change('lessonType',value||null)}/>}{input('startTime',t("Начало"),'time')}{input('endTime',t("Окончание"),'time')}{input('building',t("Корпус"))}{input('room',t("Кабинет"))}</>}</fieldset><div className="flex gap-2"><Button type="submit" disabled={busy}>{busy?t("Сохранение…"):t("Сохранить")}</Button><Button type="button" variant="outline" disabled={busy} onClick={()=>setEditing(null)}>{t("Отмена")}</Button></div></form>:<><Button variant="outline" disabled={!data} onClick={()=>{setEditing({id:'',...defaults[kind]});setNotice('')}}>{t("Добавить")}</Button><div className="space-y-2">{data?.[kind].length===0&&<p className="text-sm text-muted-foreground">{t("Пока нет записей.")}</p>}{data?.[kind].map(row=><button key={row.id} onClick={()=>{setEditing({...row});setNotice('');setError('')}} className="flex w-full min-w-0 flex-wrap items-center justify-between gap-2 rounded-lg border bg-card p-3 text-left text-sm hover:bg-muted"><span className="min-w-0 flex-1 break-words">{kind==='slots'?<>{data.subjects.find(s=>s.id===row.subjectId)?.name}<span className="mt-1 block text-xs text-muted-foreground">{days[Number(row.weekday)-1]} · {row.startTime}–{row.endTime} · {row.weekType==='both'?t("Каждая неделя"):row.weekType==='odd'?t("Числитель"):t("Знаменатель")} · {row.lessonType||t("Тип не указан")} · каб. {row.room||t("не указан")}</span></>:row.name}</span><span className="text-xs text-primary">{t("Изменить")}</span></button>)}</div></>}
 </section>
}
