import {t,useLanguage} from '../lib/language'
import {CatalogSettings} from './catalog-settings'
import {GroupImport} from './group-import'
import {useMemo,useState,type ReactNode} from 'react'
import {Copy,Share2,Search,Crown,Link2,LogOut,Pencil,Users} from 'lucide-react'
import {useGroup,ScopePicker,ScopeHelp,subgroupLabel} from './group-context'
import {useAccount} from './auth-gate'
import {Button} from './ui/button'
import {Badge} from './ui/badge'
import {Modal} from './ui/modal'
import {requestApi} from '../lib/api-client'
const roles:Record<string,string>={owner:'Владелец',head:'Староста',subhead:'Ответственный за подгруппу',member:'Участник'}
const roleOrder:Record<string,number>={owner:0,head:1,subhead:2,member:3}
export const roleLabel=(role:string)=>t(roles[role]??role)
const fill=(text:string,values:Record<string,string|number>)=>Object.entries(values).reduce((s,[k,v])=>s.split(`{${k}}`).join(String(v)),text)
type Confirm={title:string;text:string;action:string;danger?:boolean;expect?:string;done?:string;run:(typed:string)=>Promise<void>}
type Member={id:string;name:string;role:string;subgroupId:string|null;requestedSubgroupId:string|null}
const field='min-w-0 max-w-full rounded-md border bg-background p-2 text-sm'
function Section({title,icon,children,action}:{title:string;icon?:ReactNode;children:ReactNode;action?:ReactNode}){return <section className="min-w-0 space-y-3 rounded-lg border p-4"><div className="flex flex-wrap items-center justify-between gap-2"><h2 className="flex items-center gap-2 font-medium">{icon}{title}</h2>{action}</div>{children}</section>}
export function GroupPage(){
 useLanguage();
 const {data,refresh,choose,scope}=useGroup(),{user}=useAccount(),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[invite,setInvite]=useState<{url:string;code:string;expiresAt:number}|null>(null)
 const [confirm,setConfirm]=useState<Confirm|null>(null),[typed,setTyped]=useState(''),[query,setQuery]=useState(''),[editing,setEditing]=useState(''),[renaming,setRenaming]=useState(false)
 const [deleting,setDeleting]=useState<{id:string;name:string}|null>(null),[confirmation,setConfirmation]=useState('')
 async function run(fn:()=>Promise<void>,done?:string){setBusy(true);setError('');setNotice('');try{await fn();await refresh();if(done)setNotice(done)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 function ask(c:Confirm){setTyped('');setError('');setConfirm(c)}
 const me=data.member?.role??'',owner=me==='owner',admin=['owner','head'].includes(me),sub=(id:string|null)=>data.subgroups?.find(s=>s.id===id)
 const members=useMemo(()=>{const q=query.trim().toLocaleLowerCase();return [...data.members??[]].filter(m=>!q||m.name.toLocaleLowerCase().includes(q)||roleLabel(m.role).toLocaleLowerCase().includes(q)||(sub(m.subgroupId)?.name??'').toLocaleLowerCase().includes(q)).sort((a,b)=>(roleOrder[a.role]??9)-(roleOrder[b.role]??9)||a.name.localeCompare(b.name,'ru'))},[data.members,data.subgroups,query])
 const requests=(data.members??[]).filter(m=>m.requestedSubgroupId)
 // Heads cannot manage the owner or other heads; only the owner changes roles.
 const canManage=(m:Member)=>admin&&m.id!==user.id&&m.role!=='owner'&&(owner||m.role!=='head')
 const canMove=(m:Member)=>admin&&(owner||m.id===user.id||!['owner','head'].includes(m.role))
 const approve=(m:Member)=>run(async()=>{await requestApi(`/api/groups/admin/members/${m.id}/subgroup`,{method:'PATCH',body:JSON.stringify({subgroupId:m.requestedSubgroupId})})},fill(t('{name}: подгруппа назначена.'),{name:m.name}))
 async function copy(text:string){try{await navigator.clipboard.writeText(text);setNotice(t('Скопировано.'))}catch{setError(t('Не удалось скопировать. Выделите ссылку и скопируйте вручную.'))}}
 async function createInvite(){await run(async()=>{setInvite(await requestApi<{url:string;code:string;expiresAt:number}>('/api/groups/admin/invite',{method:'POST',body:'{}'}))},t('Ссылка создана. Скопируйте и отправьте одногруппникам.'))}
 const dialog=confirm&&<Modal title={confirm.title} onClose={()=>!busy&&setConfirm(null)}><form className="space-y-4" onSubmit={e=>{e.preventDefault();const c=confirm,value=typed;void run(async()=>{await c.run(value);setConfirm(null)},c.done)}}><p className="text-sm text-muted-foreground">{confirm.text}</p>{confirm.expect!==undefined&&<label className="block text-sm">{t('Введите название для подтверждения')}<input autoFocus required maxLength={100} className="mt-1 w-full rounded-md border bg-background p-2" value={typed} onChange={e=>setTyped(e.target.value)}/></label>}{error&&<p role="alert" className="text-sm text-destructive">{error}</p>}<div className="flex flex-wrap justify-end gap-2"><Button type="button" variant="outline" disabled={busy} onClick={()=>setConfirm(null)}>{t('Отмена')}</Button><Button type="submit" className={confirm.danger?'bg-destructive text-white hover:bg-destructive/90':''} disabled={busy||(confirm.expect!==undefined&&typed.trim()!==confirm.expect.trim())}>{busy?t('Подождите…'):confirm.action}</Button></div></form></Modal>
 const status=<>{error&&!confirm&&<p role="alert" className="text-sm text-destructive">{error}</p>}{notice&&<p role="status" className="text-sm text-primary">{notice}</p>}</>
 if(!data.group){
  const suggestion=data.suggestion
  return <main className="mx-auto max-w-4xl space-y-5 p-4 sm:p-6"><h1 className="text-xl font-semibold">{t('Моя группа')}</h1>{status}
   <p className="text-muted-foreground">{t('Группа даёт общее расписание, задания и УМКД для всех одногруппников. Староста создаёт группу и отправляет ссылку-приглашение.')}</p>
   {suggestion&&<Section title={fill(t('Ваша группа в Platonus: {name}'),{name:suggestion.name})} icon={<Users className="size-4"/>}><p className="text-sm text-muted-foreground">{suggestion.exists?t('Одногруппники уже пользуются группой в Campus. Попросите у старосты ссылку-приглашение и вставьте её ниже.'):t('Группы для неё в Campus пока нет. Если вы староста, создайте её — название уже подставлено.')}</p>{!suggestion.exists&&<Button disabled={busy} onClick={()=>void run(async()=>{await requestApi('/api/groups',{method:'POST',body:JSON.stringify({name:suggestion.name})});choose('common')},t('Группа создана. Пригласите одногруппников.'))}>{fill(t('Создать группу «{name}»'),{name:suggestion.name})}</Button>}</Section>}
   <Section title={t('Вступить по приглашению')} icon={<Link2 className="size-4"/>}><form className="flex flex-wrap gap-2" onSubmit={e=>{e.preventDefault();const token=String(new FormData(e.currentTarget).get('token')??'').trim();void run(async()=>{const code=/invite=([^&#\s]+)/i.exec(token)?.[1]??token,info=await requestApi<{name:string}>(`/api/groups/invitation/${encodeURIComponent(code)}`);ask({title:t('Вступить в группу?'),text:fill(t('Вы вступите в группу «{name}». Расписание группы станет доступно сразу.'),{name:info.name}),action:t('Присоединиться'),run:async()=>{await requestApi('/api/groups/join',{method:'POST',body:JSON.stringify({token})});choose('group')}})})}}><input name="token" required minLength={20} placeholder={t('Вставьте ссылку или код приглашения')} aria-label={t('Ссылка или код приглашения')} className={`${field} flex-1 basis-60`}/><Button variant="outline" disabled={busy}>{t('Проверить')}</Button></form></Section>
   <Section title={t('Создать новую группу')}><form className="flex flex-wrap gap-2" onSubmit={e=>{e.preventDefault();const name=new FormData(e.currentTarget).get('name');void run(async()=>{await requestApi('/api/groups',{method:'POST',body:JSON.stringify({name})});choose('common')},t('Группа создана. Пригласите одногруппников.'))}}><input name="name" required minLength={2} maxLength={100} defaultValue={suggestion&&!suggestion.exists?suggestion.name:''} placeholder={t('Название группы')} aria-label={t('Название группы')} className={`${field} flex-1 basis-60`}/><Button disabled={busy}>{t('Создать группу')}</Button></form><p className="text-xs text-muted-foreground">{t('Вы станете владельцем. Позже владение можно передать другому участнику.')}</p></Section>
   {dialog}</main>
 }
 const group=data.group,mine=sub(data.member?.subgroup_id??null),myRequest=data.members?.find(m=>m.id===user.id)?.requestedSubgroupId
 return <main className="mx-auto max-w-4xl space-y-5 p-4 sm:p-6">
  <header className="space-y-2">{renaming?<form className="flex flex-wrap gap-2" onSubmit={e=>{e.preventDefault();const name=new FormData(e.currentTarget).get('name');void run(async()=>{await requestApi('/api/groups/admin/group',{method:'PATCH',body:JSON.stringify({name})});setRenaming(false)},t('Название сохранено.'))}}><input name="name" autoFocus required minLength={2} maxLength={100} defaultValue={group.name} aria-label={t('Название группы')} className={`${field} flex-1 basis-60 text-base`}/><Button disabled={busy}>{t('Сохранить')}</Button><Button type="button" variant="ghost" onClick={()=>setRenaming(false)}>{t('Отмена')}</Button></form>:<div className="flex min-w-0 items-start gap-2"><h1 className="min-w-0 break-words text-xl font-semibold">{group.name}</h1>{admin&&<Button variant="ghost" size="icon" className="-mt-1 shrink-0" aria-label={t('Переименовать группу')} onClick={()=>setRenaming(true)}><Pencil/></Button>}</div>}
   <div className="flex flex-wrap gap-2 text-xs"><Badge>{roleLabel(me)}</Badge><Badge>{mine?subgroupLabel(mine.name):t('Подгруппа не назначена')}</Badge><Badge>{fill(t('Участников: {n}'),{n:data.members?.length??0})}</Badge>{data.platonusGroup&&<Badge title={t('Группа по данным Platonus участников')}>Platonus: {data.platonusGroup}</Badge>}</div></header>
  {status}
  <p className="text-sm text-muted-foreground">{t('«Для всех подгрупп» — одинаковые пары. У подгруппы задаются отличия: другая пара в это время заменяет общую. Личные оценки и подключение Platonus остаются доступны только владельцу аккаунта.')}</p>
  <div className="space-y-2"><ScopePicker purpose={t('Настроить для')}/><ScopeHelp/></div><GroupImport/>
  {!['personal','all'].includes(scope)&&['owner','head','subhead'].includes(me)&&<details className="rounded-lg border p-4"><summary className="cursor-pointer font-medium">{t('Редактировать занятия выбранной группы')}</summary><div className="pt-4"><p className="mb-3 text-sm text-muted-foreground">{t('В поле «Настроить для» выберите «Для всех подгрупп» или конкретную подгруппу. Здесь можно добавить предметы, преподавателей и регулярные пары. Разовую отмену или перенос выполняйте из карточки занятия в расписании.')}</p><CatalogSettings initialKind="slots"/></div></details>}
  <Section title={t('Моя подгруппа')}><p className="text-sm">{mine?subgroupLabel(mine.name):t('Подгруппа ещё не назначена — пока видны общие занятия.')}</p>{myRequest&&<p className="text-sm text-primary">{fill(t('Запрос отправлен: {name}. Ожидает подтверждения старосты.'),{name:sub(myRequest)?.name??''})}</p>}{!!data.subgroups?.length&&<form className="flex flex-wrap gap-2" onSubmit={e=>{e.preventDefault();const id=new FormData(e.currentTarget).get('id');void run(async()=>{await requestApi('/api/groups/subgroup-request',{method:'POST',body:JSON.stringify({id})})},t('Запрос отправлен старосте.'))}}><select name="id" aria-label={t('Желаемая подгруппа')} defaultValue={myRequest??mine?.id??data.subgroups[0]?.id} className={field}>{data.subgroups.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><Button variant="outline" disabled={busy}>{t('Запросить назначение')}</Button></form>}</Section>
  {admin&&<Section title={t('Приглашения')} icon={<Link2 className="size-4"/>}>
   <p className="text-sm text-muted-foreground">{data.invites?.active?fill(t('Действующих ссылок: {n}. Последняя действует до {date}.'),{n:data.invites.active,date:new Date(data.invites.expiresAt!).toLocaleDateString('ru-RU')}):t('Действующих ссылок нет. Создайте ссылку и отправьте её в чат группы.')}</p>
   <div className="flex flex-wrap gap-2"><Button disabled={busy} onClick={()=>void createInvite()}>{t('Создать ссылку')}</Button>{!!data.invites?.active&&<><Button variant="outline" disabled={busy} onClick={()=>ask({title:t('Создать новую ссылку?'),text:t('Все прежние ссылки перестанут работать. Уже вступившие участники останутся в группе.'),action:t('Создать новую'),done:t('Новая ссылка создана, старые отключены.'),run:async()=>{setInvite(await requestApi<{url:string;code:string;expiresAt:number}>('/api/groups/admin/invite',{method:'POST',body:JSON.stringify({replace:true})}))}})}>{t('Новая ссылка вместо старых')}</Button><Button variant="ghost" disabled={busy} onClick={()=>ask({title:t('Отключить все ссылки?'),text:t('По старым ссылкам вступить больше не получится. Участники останутся в группе.'),action:t('Отключить'),danger:true,done:t('Все ссылки отключены.'),run:async()=>{await requestApi('/api/groups/admin/invites',{method:'DELETE'});setInvite(null)}})}>{t('Отключить все ссылки')}</Button></>}</div>
   {invite&&<div className="space-y-2 rounded-md bg-muted/40 p-3"><div className="flex min-w-0 gap-2"><input readOnly value={invite.url} aria-label={t('Ссылка приглашения')} className={`${field} flex-1`} onFocus={e=>e.target.select()}/><Button variant="outline" size="icon" aria-label={t('Копировать ссылку')} onClick={()=>void copy(invite.url)}><Copy/></Button>{'share' in navigator&&<Button variant="outline" size="icon" aria-label={t('Поделиться')} onClick={()=>void navigator.share({title:group.name,url:invite.url}).catch(()=>{})}><Share2/></Button>}</div><p className="text-xs text-muted-foreground">{fill(t('Ссылка действует до {date}. Код для ручного ввода:'),{date:new Date(invite.expiresAt).toLocaleDateString('ru-RU')})} <button type="button" className="break-all font-mono underline decoration-dotted" onClick={()=>void copy(invite.code)}>{invite.code}</button></p></div>}
  </Section>}
  {admin&&requests.length>0&&<Section title={fill(t('Запросы на подгруппу: {n}'),{n:requests.length})}>{requests.map(m=><div key={m.id} className="flex flex-wrap items-center justify-between gap-2 text-sm"><span className="min-w-0 break-words">{m.name} → <b>{sub(m.requestedSubgroupId)?.name}</b></span>{canMove(m)&&<Button size="sm" disabled={busy} onClick={()=>void approve(m)}>{t('Подтвердить')}</Button>}</div>)}</Section>}
  <Section title={t('Участники')} icon={<Users className="size-4"/>}>
   {(data.members?.length??0)>3&&<label className="relative block"><Search className="pointer-events-none absolute left-2.5 top-1/2 size-4 -translate-y-1/2 text-muted-foreground"/><input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder={t('Поиск по имени, роли или подгруппе')} aria-label={t('Поиск участников')} className={`${field} w-full pl-8`}/></label>}
   {!members.length?<p className="text-sm text-muted-foreground">{query?t('Никого не нашли. Измените запрос.'):t('В группе пока только вы. Отправьте ссылку-приглашение одногруппникам.')}</p>:<ul className="divide-y">{members.map(m=><li key={m.id} className="space-y-2 py-3 first:pt-0 last:pb-0">
    <div className="flex min-w-0 flex-wrap items-center gap-2"><span className="min-w-0 break-words font-medium">{m.name}</span>{m.id===user.id&&<Badge>{t('Вы')}</Badge>}<Badge className={m.role==='owner'||m.role==='head'?'border-primary/40 text-primary':''}>{m.role==='owner'&&<Crown className="mr-1 size-3"/>}{roleLabel(m.role)}</Badge></div>
    <p className="text-sm text-muted-foreground">{sub(m.subgroupId)?subgroupLabel(sub(m.subgroupId)!.name):t('Подгруппа не назначена')}{m.requestedSubgroupId&&<span className="text-primary"> · {fill(t('просит: {name}'),{name:sub(m.requestedSubgroupId)?.name??''})}</span>}</p>
    {(canManage(m)||canMove(m)||(owner&&m.id!==user.id))&&(editing===m.id?<MemberEditor m={m} owner={owner} manage={canManage(m)} busy={busy} subgroups={data.subgroups??[]} onClose={()=>setEditing('')} onSave={(role,subgroupId)=>{const save=()=>run(async()=>{if(canManage(m))await requestApi(`/api/groups/admin/members/${m.id}`,{method:'PATCH',body:JSON.stringify({role,subgroupId})});else await requestApi(`/api/groups/admin/members/${m.id}/subgroup`,{method:'PATCH',body:JSON.stringify({subgroupId})});setEditing('')},t('Изменения сохранены.'));if(role!==m.role)ask({title:t('Изменить роль?'),text:fill(t('{name} получит роль «{role}».'),{name:m.name,role:roleLabel(role)})+(role==='head'?' '+t('Староста может приглашать и удалять участников и менять расписание всей группы.'):''),action:t('Изменить роль'),run:async()=>{await save()}});else void save()}} onRemove={canManage(m)?()=>ask({title:t('Удалить из группы?'),text:fill(t('{name} потеряет доступ к расписанию и материалам группы. Личные данные участника сохранятся.'),{name:m.name}),action:t('Удалить'),danger:true,done:fill(t('{name} удалён(а) из группы.'),{name:m.name}),run:async()=>{await requestApi(`/api/groups/admin/members/${m.id}`,{method:'DELETE'});setEditing('')}}):undefined} onTransfer={owner&&m.id!==user.id?()=>ask({title:t('Передать владение?'),text:fill(t('{name} станет владельцем группы, а вы — старостой. Отменить может только новый владелец.'),{name:m.name}),action:t('Передать владение'),danger:true,done:t('Владение передано.'),run:async()=>{await requestApi(`/api/groups/admin/transfer/${m.id}`,{method:'POST'});setEditing('')}}):undefined}/>:<Button variant="ghost" size="sm" className="-ml-3" onClick={()=>setEditing(m.id)}>{t('Управлять')}</Button>)}
   </li>)}</ul>}
  </Section>
  {admin&&<Section title={t('Подгруппы')}>{!data.subgroups?.length&&<p className="text-sm text-muted-foreground">{t('Подгрупп нет. Все участники видят общие занятия.')}</p>}{data.subgroups?.map(s=><form key={s.id} className="flex flex-wrap gap-2" onSubmit={e=>{e.preventDefault();const name=new FormData(e.currentTarget).get('name');void run(async()=>{await requestApi(`/api/groups/admin/subgroups/${s.id}`,{method:'PATCH',body:JSON.stringify({name})})},t('Название сохранено.'))}}><input className={`${field} flex-1 basis-40`} name="name" aria-label={fill(t('Название подгруппы {name}'),{name:s.name})} defaultValue={s.name} required maxLength={80}/><Button variant="outline" disabled={busy}>{t('Сохранить')}</Button><Button type="button" variant="ghost" disabled={busy} aria-label={fill(t('Удалить подгруппу {name}'),{name:s.name})} onClick={()=>{setDeleting(s);setConfirmation('');setError('')}}>{t('Удалить')}</Button></form>)}
   {deleting&&<form className="space-y-3 rounded-lg border border-destructive/40 p-4" onSubmit={e=>{e.preventDefault();void run(async()=>{await requestApi(`/api/groups/admin/subgroups/${deleting.id}`,{method:'DELETE',body:JSON.stringify({name:confirmation})});setDeleting(null);setConfirmation('');if(scope===deleting.id)choose('group')},t('Подгруппа удалена.'))}}><h3 className="font-medium">{fill(t('Удалить «{name}»?'),{name:deleting.name})}</h3><p className="text-sm text-muted-foreground">{t('Расписание, задания и другие данные этой подгруппы будут удалены без возможности восстановления. Занятия для всех и остальные подгруппы сохранятся. Если есть участники, сначала назначьте им другую подгруппу.')}</p><label className="block text-sm">{t('Введите название подгруппы')}<input autoFocus required maxLength={80} className="mt-1 w-full rounded-md border bg-background p-2" value={confirmation} onChange={e=>setConfirmation(e.target.value)}/></label><div className="flex flex-wrap gap-2"><Button type="submit" disabled={busy||confirmation.trim()!==deleting.name}>{busy?t('Удаление…'):t('Удалить подгруппу')}</Button><Button type="button" variant="outline" disabled={busy} onClick={()=>setDeleting(null)}>{t('Отмена')}</Button></div></form>}
   <form className="flex flex-wrap gap-2 border-t pt-3" onSubmit={e=>{e.preventDefault();const form=e.currentTarget,name=new FormData(form).get('name');void run(async()=>{await requestApi('/api/groups/admin/subgroups',{method:'POST',body:JSON.stringify({name})});form.reset()},t('Подгруппа добавлена.'))}}><input name="name" required maxLength={80} placeholder={t('Название новой подгруппы')} aria-label={t('Название новой подгруппы')} className={`${field} flex-1 basis-40`}/><Button variant="outline" disabled={busy}>{t('Добавить подгруппу')}</Button></form></Section>}
  <Section title={owner?t('Владение и удаление'):t('Выход из группы')} icon={<LogOut className="size-4"/>}>{owner?<><p className="text-sm text-muted-foreground">{(data.members?.length??0)>1?t('Чтобы выйти из группы, сначала передайте владение другому участнику: «Управлять» → «Передать владение».'):t('Вы единственный участник. Группу можно удалить или сначала пригласить старосту и передать ему владение.')}</p><Button variant="outline" className="text-destructive" disabled={busy} onClick={()=>ask({title:t('Удалить группу?'),text:t('Общее расписание, задания и подгруппы будут удалены у всех участников без возможности восстановления. Личные данные участников сохранятся.'),action:t('Удалить группу'),danger:true,expect:group.name,run:async value=>{await requestApi('/api/groups',{method:'DELETE',body:JSON.stringify({name:value})});choose('personal')}})}>{t('Удалить группу')}</Button></>:<><p className="text-sm text-muted-foreground">{t('После выхода общее расписание группы станет недоступно. Личные записи и Platonus сохранятся.')}</p><Button variant="outline" disabled={busy} onClick={()=>ask({title:t('Выйти из группы?'),text:t('Вернуться можно только по новой ссылке-приглашению.'),action:t('Выйти из группы'),danger:true,run:async()=>{await requestApi('/api/groups/leave',{method:'POST'});choose('personal')}})}>{t('Выйти из группы')}</Button></>}</Section>
  {dialog}
 </main>
}
function MemberEditor({m,owner,manage,busy,subgroups,onClose,onSave,onRemove,onTransfer}:{m:Member;owner:boolean;manage:boolean;busy:boolean;subgroups:{id:string;name:string}[];onClose:()=>void;onSave:(role:string,subgroupId:string|null)=>void;onRemove?:()=>void;onTransfer?:()=>void}){
 const [role,setRole]=useState(m.role),[subgroupId,setSubgroupId]=useState(m.requestedSubgroupId||m.subgroupId||'')
 const needsSubgroup=role==='subhead'&&!subgroupId
 return <div className="space-y-3 rounded-md border bg-muted/30 p-3"><div className="grid gap-2 sm:grid-cols-2">
  {manage&&<label className="grid gap-1 text-sm">{t('Роль')}<select value={role} onChange={e=>setRole(e.target.value)} disabled={!owner||busy} className={field}>{['member','subhead','head'].map(r=><option key={r} value={r}>{roleLabel(r)}</option>)}</select>{!owner&&<span className="text-xs text-muted-foreground">{t('Роли меняет владелец группы.')}</span>}</label>}
  {(manage||m.role==='owner'||m.role==='head')&&<label className="grid gap-1 text-sm">{t('Подгруппа')}<select value={subgroupId} onChange={e=>setSubgroupId(e.target.value)} disabled={busy} className={field}><option value="">{t('Подгруппа не назначена')}</option>{subgroups.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label>}
 </div>{needsSubgroup&&<p className="text-xs text-destructive">{t('Выберите подгруппу ответственного.')}</p>}
 <div className="flex flex-wrap gap-2"><Button size="sm" disabled={busy||needsSubgroup||(role===m.role&&subgroupId===(m.subgroupId??'')&&!m.requestedSubgroupId)} onClick={()=>onSave(role,subgroupId||null)}>{t('Сохранить')}</Button><Button size="sm" variant="outline" disabled={busy} onClick={onClose}>{t('Отмена')}</Button>{onTransfer&&<Button size="sm" variant="ghost" disabled={busy} onClick={onTransfer}><Crown/>{t('Передать владение')}</Button>}{onRemove&&<Button size="sm" variant="ghost" className="text-destructive" disabled={busy} onClick={onRemove}>{t('Удалить из группы')}</Button>}</div></div>
}
