import {useState} from 'react'
import {useGroup} from './group-context'
import {requestApi} from '../lib/api-client'
import {Button} from './ui/button'
import {PlatonusSchedulePreview,type PreviewRow} from './platonus-schedule-preview'
export function GroupImport(){const {data,scope}=useGroup();const [preview,setPreview]=useState<{snapshot:{id:string;weeks:number[]}|null;rows:PreviewRow[]}|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');const admin=['owner','head','subhead'].includes(data.member?.role??'')
 async function refresh(){setPreview(await requestApi('/api/groups/schedule/preview'))}
 async function run(fn:()=>Promise<void>){setBusy(true);setError('');try{await fn()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 if(scope==='personal'||scope==='all')return <p className="text-sm text-muted-foreground">Для импорта в группу выберите «Для всех подгрупп» или подгруппу в поле «Настроить для».</p>
 return <section className="space-y-3 rounded-lg border p-4"><h2 className="font-medium">Расписание из Platonus</h2><p className="text-sm text-muted-foreground">Источник назначается отдельно для общих занятий и каждой подгруппы. Импорт применяется в выбранную область. Участники своей подгруппы получают УМКД из этого источника без собственного входа. Оценки и данные входа не передаются.</p><div className="flex flex-wrap gap-2">{admin&&<Button disabled={busy} onClick={()=>void run(async()=>{await requestApi('/api/groups/schedule/source',{method:'POST'});await refresh();setNotice('Ваш Platonus назначен источником. Выберите занятия для импорта.')})}>Использовать мой Platonus</Button>}<Button variant="outline" disabled={busy} onClick={()=>void run(refresh)}>Проверить изменения</Button></div>{error&&<p role="alert" className="text-sm text-destructive">{error}</p>}{notice&&<p role="status" className="text-sm">{notice}</p>}{preview&&!preview.snapshot&&<p className="text-sm">Староста пока не подключил источник расписания.</p>}{preview?.snapshot&&admin&&<PlatonusSchedulePreview rows={preview.rows} weeks={preview.snapshot.weeks} busy={busy} onImport={rows=>void run(async()=>{let count=0;try{for(const row of rows){await requestApi('/api/groups/schedule/import',{method:'POST',body:JSON.stringify({snapshotId:preview.snapshot!.id,index:row.index,revision:row.revision})});count++}await requestApi('/api/groups/schedule/acknowledge',{method:'POST'});setNotice(`Импортировано ${count} занятий. Они доступны участникам в расписании.`)}catch(e){throw new Error(`Импортировано ${count} из ${rows.length}. ${(e as Error).message}`)}finally{await refresh()}})}/>}</section>
}
