import {t,useLanguage} from '../lib/language'
import { useCallback,useEffect,useRef,useState } from 'react'
import { Menu } from 'lucide-react'
import { requestApi } from '../lib/api-client'
import { Button } from './ui/button'
import { LessonTypeField } from './lesson-type-field'
import { LoadingState } from './ui/page-state'
type Change={confidence:number;chat_name?:string|null;sender_json?:string|null;sent_at?:string|null;provider?:string|null;id:string;action_type:string;status:string;created_at:string;applied_at:string|null;reason:string;subject_name:string|null;source_text:string|null;applied_entity_type:string|null;entity:Record<string,unknown>|null;edits:{id:string;reason:string;created_at:string;before_json:string;after_json:string}[]}
type Page={items:Change[];nextCursor:string|null}
const labels:Record<string,string>={IGNORE:'Без изменений',UNKNOWN:'Недостаточно данных',ADD_LESSON:'Добавлено занятие',ADD_HOMEWORK:'Добавлено задание',ADD_MATERIAL:'Добавлен материал',ADD_BOOK_LIST:'Добавлена литература',ADD_LINK:'Добавлена ссылка',ADD_NOTE:'Добавлена заметка',CANCEL_LESSON:'Отмена занятия',MOVE_LESSON:'Перенос занятия',CHANGE_ROOM:'Изменение кабинета',CHANGE_TIME:'Изменение времени',SET_ONLINE:'Онлайн-занятие'}
const statusLabels:Record<string,string>={applied:'Выполнено',reverted:'Отменено',suggested:'Требует проверки',rejected:'Отклонено'}
const fields:Record<string,[string,string,string][]>={homework:[['title','Задание','text'],['description','Описание','text'],['due_at','Срок','date']],material:[['title','Название','text'],['description','Описание','text'],['url','Ссылка','url']],schedule_slot:[['lesson_type','Тип занятия','type'],['room','Кабинет','text'],['building','Корпус','text'],['start_time','Начало','time'],['end_time','Окончание','time']],lesson_override:[['note','Заметка','text'],['room','Кабинет','text'],['building','Корпус','text'],['moved_start_time','Начало','time'],['moved_end_time','Окончание','time'],['online_url','Ссылка','url']]}
export function HistoryPage({onMenuClick,onRefresh}:{onMenuClick:()=>void;onRefresh:()=>unknown}){
 useLanguage();
 const [page,setPage]=useState<Page|null>(null),[cursor,setCursor]=useState<string|undefined>(),[error,setError]=useState(''),[busy,setBusy]=useState(false),[editing,setEditing]=useState<string|null>(null),[patch,setPatch]=useState<Record<string,unknown>>({}),[reason,setReason]=useState(''),[scope,setScope]=useState('changes')
 const sequence=useRef(0)
 const load=useCallback(async()=>{const request=++sequence.current;setBusy(true);try{const result=await requestApi<Page>(`/api/changes?scope=${scope}${cursor?`&before=${encodeURIComponent(cursor)}`:''}`);if(request===sequence.current){setPage(result);setError('')}}catch(e){if(request===sequence.current)setError(e instanceof Error?e.message:'Ошибка загрузки')}finally{if(request===sequence.current)setBusy(false)}},[cursor,scope])
 useEffect(()=>{void load();return()=>{sequence.current++}},[load])
 async function mutate(path:string,method:string,body?:unknown){setBusy(true);try{await requestApi(path,{method,...(body?{body:JSON.stringify(body)}:{})});setEditing(null);await load();void onRefresh()}catch(e){setError(e instanceof Error?e.message:'Ошибка изменения')}finally{setBusy(false)}}
 return <main className="mx-auto max-w-4xl space-y-5 px-4 py-5 sm:px-6"><header className="flex items-start gap-3"><Button variant="ghost" size="icon" className="-ml-2 shrink-0 md:hidden" onClick={onMenuClick} aria-label={t("Открыть меню")}><Menu/></Button><div className="min-w-0"><h1 className="text-xl font-semibold">{t("История изменений")}</h1><p className="mt-1 text-sm text-muted-foreground">{t("Что изменил AI, на основании каких сообщений, и ваши правки.")}</p></div></header><nav className="-mx-4 overflow-x-auto px-4 sm:mx-0 sm:px-0" aria-label={t("Виды истории")}><div className="flex min-w-max gap-1 rounded-lg border bg-card p-1 sm:inline-flex">{[['changes','Изменения'],['all','Решения AI'],['activity','Журнал действий']].map(([value,label])=><button key={value} type="button" aria-pressed={scope===value} className={scope===value?'h-10 flex-1 whitespace-nowrap rounded-md bg-primary px-3 text-sm font-medium text-primary-foreground':'h-10 flex-1 whitespace-nowrap rounded-md px-3 text-sm font-medium text-muted-foreground hover:bg-muted hover:text-foreground'} onClick={()=>{setScope(value);setCursor(undefined);setEditing(null)}}>{t(label)}</button>)}</div></nav>{scope==='activity'?<ActivityLog/>:<>{error&&<p role="alert" className="text-sm text-destructive">{error}</p>}{!page&&!error&&<LoadingState/>}{page?.items.length===0&&<p className="rounded-lg border p-5 text-sm text-muted-foreground">Изменений пока нет.</p>}
 {page?.items.map(item=><article key={item.id} className="space-y-3 rounded-lg border bg-card p-4"><div className="flex flex-wrap justify-between gap-2"><h2 className="min-w-0 break-words text-sm font-semibold">{labels[item.action_type]??item.action_type}{item.subject_name?` · ${item.subject_name}`:''}</h2><span className="text-xs text-muted-foreground">{statusLabels[item.status]??item.status}</span></div><p className="text-xs text-muted-foreground">Создано: {new Date(item.created_at).toLocaleString('ru-RU')}{item.applied_at?` · Выполнено: ${new Date(item.applied_at).toLocaleString('ru-RU')}`:''}</p><p className="break-words text-sm">{item.reason}</p><p className="text-xs text-muted-foreground">Уверенность: {Math.round(item.confidence*100)}%{item.provider?` · ${item.provider} · ${item.chat_name??''}`:' · Личный чат'}</p><DecisionEvidence id={item.id}/>{item.source_text&&<details className="text-sm"><summary className="cursor-pointer text-muted-foreground">Исходное сообщение</summary><p className="mt-2 text-xs text-muted-foreground">{item.sender_json?JSON.parse(item.sender_json).name: t("Вы")}{item.sent_at?` · ${new Date(item.sent_at).toLocaleString('ru-RU')}`:''}</p><p className="mt-2 whitespace-pre-wrap break-words">{item.source_text}</p></details>}
 {item.entity&&<p className="whitespace-pre-wrap break-words text-sm text-muted-foreground">{Object.entries(item.entity).filter(([key,value])=>fields[item.applied_entity_type??'']?.some(([k])=>k===key)&&value).map(([key,value])=>`${fields[item.applied_entity_type!].find(([k])=>k===key)?.[1]}: ${value}`).join('\n')}</p>}
 <EditHistory key={item.edits[0]?.id??item.id} id={item.id} kind={item.applied_entity_type??''} initial={item.edits}/>
 {editing===item.id&&item.entity?<form className="space-y-3 border-t pt-3" onSubmit={e=>{e.preventDefault();void mutate(`/api/changes/${item.id}/entity`,'PATCH',{patch,reason})}}><div className="grid gap-3 sm:grid-cols-2">{fields[item.applied_entity_type??'']?.map(([key,label,type])=>{const current=key in patch?patch[key]:item.entity![key];return type==='type'?<LessonTypeField key={key} value={String(current??'')} onChange={value=>setPatch(p=>({...p,[key]:value||null}))}/>:<label key={key} className="text-sm">{label}<input className="mt-1 w-full rounded-md border bg-background p-2 text-sm" type={type} value={type==='date'?String(current??'').slice(0,10):String(current??'')} onChange={e=>setPatch(p=>({...p,[key]:e.target.value?(type==='date'?`${e.target.value}T23:59:00.000Z`:e.target.value):null}))}/></label>})}</div><label className="block text-sm">Причина правки<input required value={reason} onChange={e=>setReason(e.target.value)} className="mt-1 w-full rounded-md border bg-background p-2" maxLength={1000}/></label><div className="flex gap-2"><Button disabled={busy||!Object.keys(patch).length||!reason.trim()}>{t("Сохранить")}</Button><Button type="button" variant="outline" onClick={()=>setEditing(null)}>{t("Отмена")}</Button></div></form>:item.status==='applied'&&<div className="flex flex-wrap gap-2"><Button variant="outline" disabled={busy||!item.entity} onClick={()=>{setEditing(item.id);setPatch({});setReason('')}}>{t("Редактировать")}</Button><Button variant="outline" disabled={busy} onClick={()=>void mutate(`/api/actions/${item.id}/revert`,'POST')}>Откатить изменение</Button></div>}
 </article>)}<div className="flex gap-2">{cursor&&<Button variant="outline" disabled={busy} onClick={()=>{setEditing(null);setCursor(undefined)}}>К последним</Button>}{page?.nextCursor&&<Button variant="outline" disabled={busy} onClick={()=>{setEditing(null);setCursor(page.nextCursor!)}}>Предыдущие 20 изменений</Button>}</div></>}</main>
}

function EditHistory({id,kind,initial}:{id:string;kind:string;initial:Change['edits']}){
 useLanguage();
 const [edits,setEdits]=useState(initial),[older,setOlder]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('')
 return <div className="space-y-2"> {edits.map(edit=><details key={edit.id} className="rounded-md bg-muted p-2 text-xs"><summary className="cursor-pointer">Правка {new Date(edit.created_at).toLocaleString('ru-RU')} · {edit.reason}</summary><p className="mt-2 whitespace-pre-wrap break-words">{(()=>{const before=JSON.parse(edit.before_json),after=JSON.parse(edit.after_json);return Object.keys(after).filter(k=>k!=='updated_at'&&after[k]!==before[k]).map(k=>`${fields[kind]?.find(([key])=>key===k)?.[1]??k}: ${before[k]??'—'} → ${after[k]??'—'}`).join('\n')})()}</p></details>)}{error&&<p role="alert" className="text-xs text-destructive">{error}</p>}{(older?edits.length===20:edits.length===10)&&<Button size="sm" variant="ghost" disabled={busy} onClick={()=>{const last=edits.at(-1)!;setBusy(true);void requestApi<Change['edits']>(`/api/changes/${id}/edits?before=${encodeURIComponent(`${last.created_at}|${last.id}`)}`).then(rows=>{setEdits(rows);setOlder(true)}).catch(e=>setError(e.message)).finally(()=>setBusy(false))}}>Более ранние правки</Button>}{older&&<Button size="sm" variant="ghost" onClick={()=>{setEdits(initial);setOlder(false)}}>Последние правки</Button>}</div>
}

type Evidence={assistant_message_id:string|null;validation_status:string;validation_errors_json:string;auto_applied:number;evidence:{currentMessageId:string;threshold:number;trustedSender:boolean;autoApplyEnabled:boolean;model:string;subjectCandidates:{subjectName:string;evidence:string}[]}|null;messages:{id:string;text:string|null;sender_json:string;sent_at:string}[]}
function DecisionEvidence({id}:{id:string}){
 useLanguage();
 const [data,setData]=useState<Evidence|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false)
 const load=()=>{if(data||busy)return;setBusy(true);setError('');void requestApi<Evidence>(`/api/changes/${id}/evidence`).then(setData).catch(e=>setError(e.message)).finally(()=>setBusy(false))}
 const sources:Record<string,string>={explicit_subject:'предмет назван прямо',explicit_teacher:'назван преподаватель',explicit_date:'дата сообщения',reply_context:'ответ на сообщение',neighbor_message:'соседние сообщения',active_lesson:'текущее занятие',nearest_lesson:'ближайшее занятие'}
 return <details className="text-sm" onToggle={e=>{if(e.currentTarget.open)load()}}><summary className="cursor-pointer text-muted-foreground">Основания решения и контекст</summary><div className="mt-3 space-y-3">{busy&&<LoadingState/>}{error&&<p role="alert">{error}<Button variant="outline" onClick={load}>{t("Повторить")}</Button></p>}{data&&<><p className="text-xs text-muted-foreground">Здесь показаны факты, переданные модели, и результаты проверок. Просмотр журнала не меняет уверенность.</p><p>Проверка: {data.validation_status==='valid'?'пройдена':data.validation_status}. {data.auto_applied?'Применено автоматически.':'Автоматически не применялось.'}</p>{data.validation_errors_json!=='[]'&&<p className="break-words">{JSON.parse(data.validation_errors_json).join(' · ')}</p>}{data.evidence?<><p className="text-xs text-muted-foreground">Модель: {data.evidence.model} · Порог: {Math.round(data.evidence.threshold*100)}% · Источник {data.evidence.trustedSender?'доверенный':'не отмечен доверенным'} · Автоприменение {data.evidence.autoApplyEnabled?'включено':'выключено'}</p><p className="text-xs">{data.evidence.subjectCandidates.map(c=>`${c.subjectName}: ${sources[c.evidence]??c.evidence}`).join('; ')}</p><p className="text-xs text-muted-foreground">Кандидаты выше — подсказки для выбора предмета, а не подтверждение, что модель использовала каждую из них.</p>{data.messages.map(m=><div key={m.id} className="rounded-md border p-3"><p className="text-xs text-muted-foreground">{JSON.parse(m.sender_json).name??'Отправитель'} · {new Date(m.sent_at).toLocaleString('ru-RU')}{m.id===data.evidence!.currentMessageId?' · Исходное сообщение':' · Контекст'}</p><p className="mt-1 whitespace-pre-wrap break-words">{m.text}</p></div>)}</>:<p>{data.assistant_message_id?'Прямая команда владельца из личного AI-чата.':'Для этой старой записи снимок контекста не сохранялся.'}</p>}</>}</div></details>
}
function ActivityLog(){
 useLanguage();
 const [page,setPage]=useState<{items:{id:string;action:string;actor_type:string;entity_type:string;entity_id:string;created_at:string;metadata_json:string}[];nextCursor:string|null}|null>(null),[cursor,setCursor]=useState<string|null>(null),[error,setError]=useState('')
 useEffect(()=>{setPage(null);void requestApi<NonNullable<typeof page>>(`/api/activity${cursor?`?before=${encodeURIComponent(cursor)}`:''}`).then(setPage).catch(e=>setError(e.message))},[cursor])
 const actions:Record<string,string>={'platonus.imported':'Импортировано занятие из Platonus','platonus.reverted':'Отменён импорт Platonus','ai_run.queued':'Запущен анализ','ai_action.applied':'Применено решение AI','ai_action.reverted':'Откачено изменение','ai_action.edited':'Исправлено решение AI','ai_action.rejected':'Отклонено решение AI','catalog.created':'Добавлена запись в справочник','catalog.updated':'Изменён справочник','homework.created':'Добавлено задание','homework.updated':'Изменено задание','material.created':'Добавлен материал','attachment.created':'Загружен файл','lesson_override.created':'Изменено занятие','lesson_override.updated':'Исправлено занятие','settings.updated':'Изменены настройки','integration.pairing_started':'Начато подключение','integration.disconnected':'Отключён мессенджер','integration.connected':'Подключён мессенджер','people.updated':'Изменена карточка человека','people.created':'Добавлен человек','people.linked':'Связаны аккаунты человека','source.selected':'Изменён выбор чата'}
 const actors:Record<string,string>={user:'Вы',system:'Система',cron:'По расписанию',integration:'Мессенджер'}
 return <section className="space-y-3"><p className="text-sm text-muted-foreground">Сохранённые события приложения: запуск анализа, применение, откат и другие действия. Подробные правки доступны в разделе «Изменения».</p>{error&&<p role="alert">{error}</p>}{!page&&!error&&<LoadingState/>}{page?.items.map(row=><article key={row.id} className="rounded-lg border p-3 text-sm"><p>{actions[row.action]??row.action} · {actors[row.actor_type]??row.actor_type}</p><p className="text-xs text-muted-foreground">{new Date(row.created_at).toLocaleString('ru-RU')} · {row.entity_type}</p>{row.metadata_json!=='{}'&&<details><summary className="cursor-pointer">Данные события</summary><pre className="whitespace-pre-wrap break-all text-xs">{JSON.stringify(JSON.parse(row.metadata_json),null,2)}</pre></details>}</article>)}{page?.items.length===0&&<p>Событий пока нет.</p>}<div className="flex gap-2">{cursor&&<Button variant="outline" onClick={()=>setCursor(null)}>К последним</Button>}{page?.nextCursor&&<Button variant="outline" onClick={()=>setCursor(page.nextCursor)}>Предыдущие 20 событий</Button>}</div></section>
}
