import {t,useLanguage} from '../lib/language'
import { useEffect, useState } from 'react'
import { requestApi } from '../lib/api-client'
import { Button } from './ui/button'
import { LoadingState } from './ui/page-state'
type Person = { id: string; name: string; nickname: string | null; role: string; trusted: number | boolean }
type Identity = { provider: 'telegram' | 'whatsapp'; senderId: string; personId?: string; name?: string; username?:string|null; phone?:string|null; lastSeenAt?:string }
type PeopleData = { people: Person[]; identities: Identity[]; senders: Identity[] }
const roles: Record<string,string> = { student: 'Студент', head: 'Староста', curator: 'Куратор', teacher: 'Преподаватель', other: 'Другая роль' }
const field = 'mt-1 w-full rounded-md border bg-background px-3 py-2 text-sm'
export function PeopleSettings() {
 useLanguage();
  const [data, setData] = useState<PeopleData | null>(null), [error, setError] = useState(''), [busy, setBusy] = useState(false)
  const [draft, setDraft] = useState<Person>({ id: '', name: '', nickname: '', role: 'student', trusted: false })
  const [selected, setSelected] = useState<Identity[]>([]),[search,setSearch]=useState(''),[mergeSource,setMergeSource]=useState('')
  const [manual, setManual] = useState<Identity>({ provider: 'telegram', senderId: '' })
  const refresh = () => requestApi<PeopleData>('/api/people').then(setData)
  useEffect(() => { void refresh().catch((e) => setError(e.message)) }, [])
  async function save(event: React.FormEvent) {
    event.preventDefault(); setBusy(true); setError('')
    try {
      const { id, ...values } = draft
      const person = await requestApi<{ id: string }>(id ? `/api/people/${id}` : '/api/people', { method: id ? 'PATCH' : 'POST', body: JSON.stringify({ ...values, trusted: Boolean(values.trusted) }) })
      setDraft({ ...draft, id: person.id })
      await requestApi(`/api/people/${person.id}/identities`, { method: 'PUT', body: JSON.stringify(selected.map(({ provider, senderId }) => ({ provider, senderId }))) })
      await refresh(); setDraft({ id: '', name: '', nickname: '', role: 'student', trusted: false }); setSelected([])
    } catch (reason) { setError(reason instanceof Error ? reason.message : 'Не удалось сохранить') } finally { setBusy(false) }
  }
  const candidates = [...(data?.senders ?? []), ...(data?.identities ?? []), ...selected].filter((item, index, all) => all.findIndex((other) => other.provider === item.provider && other.senderId === item.senderId) === index)
  const query=search.toLocaleLowerCase()
  const match=(s:Identity)=>[s.name,s.username,s.phone,s.senderId].some(value=>value?.toLocaleLowerCase().includes(query))
  const unlinked=(data?.senders??[]).filter(s=>!data?.identities.some(i=>i.provider===s.provider&&i.senderId===s.senderId))
  const phoneMatches=candidates.filter(s=>s.phone&&selected.some(i=>i.provider!==s.provider&&candidates.find(c=>c.provider===i.provider&&c.senderId===i.senderId)?.phone===s.phone)&&!selected.some(i=>i.provider===s.provider&&i.senderId===s.senderId))
  return <section className="space-y-4"><h2 className="text-base font-semibold">{t("Люди и роли")}</h2><p className="text-sm text-muted-foreground">Привяжите отправителей Telegram и WhatsApp к одной карточке. Совпадение имени само по себе не объединяет людей.</p>
    {error && <p role="alert" className="text-sm text-destructive">{error}</p>}
    {!data && !error && <LoadingState />}
    <label className="block text-sm">Поиск по имени, нику или номеру<input value={search} onChange={e=>setSearch(e.target.value)} className={field}/></label>
    <div className="space-y-2"><h3 className="text-sm font-medium">Новые отправители · {unlinked.length}</h3><p className="text-xs text-muted-foreground">Список пополняется автоматически из выбранных чатов. Номера видны только когда мессенджер их предоставляет.</p>{unlinked.filter(match).slice(0,50).map(sender=><button key={`${sender.provider}:${sender.senderId}`} className="block w-full rounded-lg border p-3 text-left text-sm" onClick={()=>{setDraft({id:'',name:(sender.name??sender.senderId).slice(0,120),nickname:sender.username??'',role:'student',trusted:false});setSelected([sender])}}>{sender.name??sender.senderId}<span className="block text-xs text-muted-foreground">{sender.provider} · {sender.phone??sender.username??sender.senderId} · Создать карточку</span></button>)}{unlinked.filter(match).length>50&&<p className="text-xs text-muted-foreground">Уточните поиск, чтобы найти других отправителей.</p>}</div>
    <div className="space-y-2">{data?.people.filter(p=>[p.name,p.nickname].some(v=>v?.toLocaleLowerCase().includes(query))).map((person) => <button key={person.id} onClick={() => { setDraft(person); setSelected(data.identities.filter((item) => item.personId === person.id)) }} className="w-full rounded-lg border bg-card p-3 text-left"><span className="break-words font-medium">{person.name}{person.nickname ? ` · ${person.nickname}` : ''}</span><span className="ml-2 text-xs text-muted-foreground">{roles[person.role]}{person.trusted ? ' · Доверенный источник' : ''}</span></button>)}</div>
    <form onSubmit={save} className="space-y-4 rounded-lg border bg-card p-4"><h3 className="text-sm font-semibold">{draft.id ? 'Изменить карточку' : 'Новый человек'}</h3>
      <div className="grid gap-3 sm:grid-cols-2"><label className="text-sm">Имя<input required maxLength={120} value={draft.name} onChange={(e) => setDraft({ ...draft, name: e.target.value })} className={field} /></label><label className="text-sm">Никнейм<input maxLength={120} value={draft.nickname ?? ''} onChange={(e) => setDraft({ ...draft, nickname: e.target.value })} className={field} /></label><label className="text-sm">Роль<select value={draft.role} onChange={(e) => setDraft({ ...draft, role: e.target.value })} className={field}>{Object.entries(roles).map(([key,label]) => <option key={key} value={key}>{label}</option>)}</select></label></div>
      <label className="flex items-start gap-2 text-sm"><input type="checkbox" checked={Boolean(draft.trusted)} onChange={(e) => setDraft({ ...draft, trusted: e.target.checked })} className="mt-0.5 size-5 shrink-0 accent-blue-600" /><span>Доверять объявлениям об изменении расписания<span className="mt-1 block text-xs text-muted-foreground">Автоприменение всё равно зависит от настроек, проверки данных и отсутствия признаков шутки.</span></span></label>
      {phoneMatches.length>0&&<div className="rounded-md border p-3 text-sm"><p className="font-medium">Совпадает номер телефона</p>{phoneMatches.map(sender=><p key={`${sender.provider}:${sender.senderId}`} className="mt-2">{sender.name} · {sender.provider} · {sender.phone}<Button type="button" variant="outline" size="sm" disabled={data?.identities.some(i=>i.provider===sender.provider&&i.senderId===sender.senderId&&i.personId!==draft.id)} onClick={()=>setSelected([...selected,sender])}>Это тот же человек</Button></p>)}<p className="mt-2 text-xs text-muted-foreground">Связь подтверждаете вы. Роль и доверие не назначаются по совпадению номера.</p></div>}
      <fieldset className="space-y-2"><legend className="mb-2 text-sm font-medium">Отправители этого человека</legend>{candidates.filter(s=>match(s)||selected.some(i=>i.provider===s.provider&&i.senderId===s.senderId)).map((sender) => {
        const linked = data?.identities.find((item) => item.provider === sender.provider && item.senderId === sender.senderId)
        return <label key={`${sender.provider}:${sender.senderId}`} className="flex min-h-11 items-start gap-2 break-all py-1 text-sm"><input type="checkbox" className="mt-0.5 size-5 shrink-0 accent-blue-600" disabled={Boolean(linked && linked.personId !== draft.id)} checked={selected.some((item) => item.provider === sender.provider && item.senderId === sender.senderId)} onChange={(e) => setSelected(e.target.checked ? [...selected, sender] : selected.filter((item) => item.provider !== sender.provider || item.senderId !== sender.senderId))} /><span>{sender.name ?? sender.senderId} · {sender.provider} · {sender.phone??sender.senderId}{linked && linked.personId !== draft.id ? ' (уже привязан)' : ''}</span></label>
      })}</fieldset>
      <div className="flex flex-wrap items-end gap-2"><label className="min-w-32 flex-1 basis-32 text-xs">Мессенджер<select value={manual.provider} className={field} onChange={(e) => setManual({ ...manual, provider: e.target.value as Identity['provider'] })}><option value="telegram">Telegram</option><option value="whatsapp">WhatsApp</option></select></label><label className="min-w-40 flex-1 basis-40 text-xs">ID отправителя<input className={field} value={manual.senderId} maxLength={160} onChange={(e) => setManual({ ...manual, senderId: e.target.value })} /></label><Button type="button" variant="outline" disabled={!manual.senderId.trim()} onClick={() => { if (!selected.some((i) => i.provider === manual.provider && i.senderId === manual.senderId.trim())) setSelected([...selected, { ...manual, senderId: manual.senderId.trim() }]); setManual({ ...manual, senderId: '' }) }}>Привязать</Button></div>
      <div className="flex flex-wrap gap-2"><Button type="submit" disabled={busy}>{t("Сохранить")}</Button>{draft.id && <Button type="button" variant="outline" onClick={() => { setDraft({ id: '', name: '', nickname: '', role: 'student', trusted: false }); setSelected([]) }}>Новая карточка</Button>}</div>
    </form>{draft.id&&<div className="space-y-2 rounded-lg border p-4"><label className="block text-sm">Объединить с другой карточкой<select className={field} value={mergeSource} onChange={e=>setMergeSource(e.target.value)}><option value="">Выберите человека</option>{data?.people.filter(p=>p.id!==draft.id).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><p className="text-xs text-muted-foreground">Все аккаунты выбранной карточки будут перенесены в «{draft.name}». Имя, роль и доверие текущей карточки сохранятся.</p><Button type="button" variant="outline" disabled={busy||!mergeSource} onClick={()=>{setBusy(true);void requestApi(`/api/people/${draft.id}/merge`,{method:'POST',body:JSON.stringify({sourceId:mergeSource})}).then(async()=>{const next=await requestApi<PeopleData>('/api/people');setData(next);setSelected(next.identities.filter(i=>i.personId===draft.id));setMergeSource('')}).catch(e=>setError(e.message)).finally(()=>setBusy(false))}}>Это один человек — объединить</Button></div>}</section>
}
