import {t,useLanguage} from '../lib/language'
import {PlatonusSchedulePreview} from './platonus-schedule-preview'
import {PlatonusUmkd} from './platonus-umkd'
import { useEffect, useState } from 'react'
import { Menu,RefreshCw } from 'lucide-react'
import { requestApi } from '../lib/api-client'
import { Button } from './ui/button'
import { LoadingState } from './ui/page-state'
import type { PlatonusLesson, PlatonusSnapshot, StudySection } from '../../bridge/platonus-parser'
type PreviewRow={index:number;lesson:PlatonusLesson;weekType:string;status:string;revision:string;existing:Record<string,unknown>|null;collisions:Record<string,unknown>[]}
type Data={snapshot:(PlatonusSnapshot&{id:string})|null;rows:PreviewRow[];imports:{id:string;before_json:string|null;after_json:string;source_json:string;created_at:string;reverted_at:string|null}[]}
type Connection={status:string;needsCode:boolean;lastSyncAt:string|null;error:string|null;automaticSync:string;scheduleChanged?:boolean;credentialsSaved?:boolean}
const days=['','Пн','Вт','Ср','Чт','Пт','Сб','Вс']
const stamp=(v:string)=>new Date(v).toLocaleString('ru-RU')
function StudyData({section}:{section:StudySection & {capturedAt?:string|null}}){
 useLanguage();return <div className="space-y-4">{section.error&&<p role="status" className="text-sm text-amber-700 dark:text-amber-300">{section.error}</p>}{section.capturedAt&&<p className="text-xs text-muted-foreground">Снимок данных: {stamp(section.capturedAt)}</p>}{!section.tables.length&&!section.error&&<p className="text-sm text-muted-foreground">В Platonus пока нет данных.</p>}{section.tables.map((table,i)=><section key={i} className="space-y-2"><h2 className="font-medium">{table.title}</h2><div tabIndex={0} role="region" aria-label={table.title} className="overflow-x-auto rounded-lg border focus-visible:outline focus-visible:outline-2 focus-visible:outline-primary"><table className="w-full text-sm"><caption className="sr-only">Таблица из Platonus</caption>{table.headers.length>0&&<thead><tr>{table.headers.map((header,k)=><th key={k} scope="col" className="p-3 text-left font-medium">{header}</th>)}</tr></thead>}<tbody>{table.rows.map((row,j)=><tr key={j} className="border-t">{row.map((cell,k)=><td key={k} className="min-w-24 max-w-sm break-words p-3 align-top">{cell||'—'}</td>)}</tr>)}</tbody></table></div></section>)}{section.links.length>0&&<ul className="space-y-2">{section.links.map((link,i)=><li key={i}><a className="break-words text-sm text-primary underline" href={link.url} target="_blank" rel="noreferrer">{link.title}</a></li>)}</ul>}</div>}
export function PlatonusPage({onMenuClick,initialTab='schedule',embedded=false}:{onMenuClick:()=>void;initialTab?:string;embedded?:boolean}){
 useLanguage();
 const Container=embedded?'section':'main'
 const [tab,setTab]=useState(initialTab),[data,setData]=useState<Data|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState('')
 const [connection,setConnection]=useState<Connection|null>(null),[login,setLogin]=useState(''),[password,setPassword]=useState(''),[remember,setRemember]=useState(false),[code,setCode]=useState('')
 async function refresh(){setData(await requestApi<Data>('/api/platonus'))}
 async function action(name:string,body:unknown={}){setConnection(await requestApi<Connection>(`/api/platonus/${name}`,{method:'POST',body:JSON.stringify(body)}))}
 async function run(action:()=>Promise<void>){setBusy(true);setError('');try{await action()}catch(e){setError(e instanceof Error?e.message:'Ошибка')}finally{setBusy(false)}}
 useEffect(()=>{
  let active=true,timer:ReturnType<typeof setTimeout>|undefined,previous=''
  const poll=async()=>{try{const result=await requestApi<Connection>('/api/platonus/connection');if(!active)return;setConnection(result);if(previous!==String(result.lastSyncAt)){await refresh();previous=String(result.lastSyncAt)}}catch(e){if(active)setError(e instanceof Error?e.message:'Нет связи')}finally{if(active)timer=setTimeout(poll,5000)}}
  void poll();return()=>{active=false;clearTimeout(timer)}
 },[])
 const working=busy||connection?.status==='syncing'
 const connected=connection?.status==='connected'||connection?.status==='syncing'
 return <Container className={embedded?'min-w-0 space-y-5':'mx-auto max-w-5xl space-y-5 p-4 sm:p-6'}>{!embedded&&<header className="flex items-center gap-3"><Button variant="ghost" size="icon" className="md:hidden" onClick={onMenuClick} aria-label={t("Открыть меню")}><Menu/></Button><h1 className="text-xl font-semibold">{initialTab==='grades'?t("Оценки"):initialTab==='umkd'?t("УМКД"):'Platonus'}</h1></header>}
 {(initialTab==='schedule'||(!connected&&!connection?.credentialsSaved))&&<details open={!connected||initialTab==='schedule'} className="rounded-lg border"><summary className="cursor-pointer p-3 text-sm font-medium">Подключение Platonus</summary><section className="space-y-3 bg-card p-4"><h2 className="font-medium">Аккаунт университета</h2>
 <p className="text-sm text-muted-foreground">Автоматическое обновление каждый час работает при сохранённых данных входа. При отключении Platonus сохранённые данные входа удаляются. Расписание, оценки и документы остаются в Campus.</p>
 {(!connected||!connection?.credentialsSaved)&&<form className="space-y-3" onSubmit={e=>{e.preventDefault();void run(async()=>{const value=password;setPassword('');await action('login',{login,password:value,remember});if(!remember)setLogin('')})}}>
 <div className="grid gap-3 sm:grid-cols-2"><label className="text-sm">Логин Platonus<input required autoComplete="username" value={login} onChange={e=>setLogin(e.target.value)} className="mt-1 w-full rounded-md border bg-background px-3 py-2"/></label><label className="text-sm">Пароль Platonus<input required type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} className="mt-1 w-full rounded-md border bg-background px-3 py-2"/></label></div>
 <label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={remember} onChange={e=>setRemember(e.target.checked)}/>{t("Запомнить данные входа")}</label><p className="text-xs text-muted-foreground">{t("С галочкой Campus сохраняет логин и пароль зашифрованными и обновляет данные автоматически. Без неё для каждого обновления нужно входить заново.")}</p><Button disabled={working} type="submit">{busy?'Подключение…':t("Подключить Platonus")}</Button></form>}
 {connection?.needsCode&&<form className="flex flex-wrap items-end gap-3" onSubmit={e=>{e.preventDefault();void run(async()=>{await action('verify',{code});setCode('')})}}><label className="text-sm">Код подтверждения Platonus<input required inputMode="numeric" autoComplete="one-time-code" value={code} onChange={e=>setCode(e.target.value)} className="mt-1 block rounded-md border bg-background px-3 py-2"/></label><Button disabled={working} type="submit">Подтвердить код</Button></form>}
 {connected&&<div className="flex flex-wrap gap-2"><Button disabled={working} onClick={()=>void run(()=>action('sync'))}>{connection?.status==='syncing'?'Получение данных…':'Обновить сейчас'}</Button><Button variant="outline" disabled={busy} onClick={()=>void run(()=>action('disconnect'))}>{t("Отключить Platonus")}</Button></div>}
 <p role="status" className="text-sm text-muted-foreground">{connection?.status==='syncing'?'Получаем расписание, оценки и УМКД…':connected?t("Platonus подключён"):connection?.status==='expired'?'Сессия истекла. Введите логин и пароль повторно.':connection?.needsCode?'Введите код, отправленный Platonus.':'Войдите своим университетским аккаунтом.'}</p>
 {connection?.error&&<p role="alert" className="text-sm text-destructive">{connection.error}</p>}
 </section></details>}
 {notice&&<p role="status" className="text-sm text-primary">{notice}</p>}
 {error&&<div role="alert" className="space-y-2 text-sm text-destructive"><p>{error}</p><Button variant="outline" disabled={busy} onClick={()=>void run(refresh)}>Повторить загрузку</Button></div>}
 {initialTab==='schedule'&&<nav aria-label="Разделы Platonus" className="flex flex-wrap gap-2">{[['schedule','Расписание'],['grades','Оценки'],['umkd','УМКД'],['imports','История импорта']].map(([id,name])=><Button key={id} variant={tab===id?'default':'outline'} aria-pressed={tab===id} onClick={()=>setTab(id)}>{name}</Button>)}</nav>}
 {['grades','umkd'].includes(tab)&&<div className="flex flex-wrap items-center gap-3"><Button variant="ghost" size="icon" title={t("Обновить данные")} aria-label={t("Обновить данные")} disabled={working||!connected} onClick={()=>void run(()=>action('sync'))}><RefreshCw className={working?'size-4 animate-spin':'size-4'}/></Button><p className="text-xs text-muted-foreground">{connection?.lastSyncAt?'Последнее обновление: '+stamp(connection.lastSyncAt):'Данные ещё не получены'}</p></div>}
 {connection?.scheduleChanged&&<div role="status" className="rounded-lg border border-primary/30 p-4"><p>В Platonus изменилось расписание. Проверьте изменения перед импортом.</p><Button variant="outline" onClick={()=>window.dispatchEvent(new Event('campus-review-schedule'))}>Проверить расписание</Button></div>}
 {!data&&!error&&<LoadingState/>}{data&&!data.snapshot&&<p className="text-sm text-muted-foreground">После входа данные загрузятся автоматически. Расписание сначала появится здесь для проверки.</p>}
 {data?.snapshot&&<>{tab==='schedule'&&<p className="text-xs text-muted-foreground">Получено {stamp(data.snapshot.capturedAt)} · Семестр {data.snapshot.semesterStart} — {data.snapshot.semesterEnd} · Недели {data.snapshot.weeks.join(' и ')}</p>}
 {tab==='schedule'&&<PlatonusSchedulePreview key={data.snapshot.id} rows={data.rows} weeks={data.snapshot.weeks} busy={busy} onImport={rows=>void run(async()=>{setNotice('');let completed=0;try{for(const row of rows){await requestApi('/api/platonus/import',{method:'POST',body:JSON.stringify({snapshotId:data.snapshot!.id,index:row.index,revision:row.revision})});completed++}setNotice(`Импортировано занятий: ${completed}. Откройте «Расписание» в главном меню. Откат доступен в истории импорта.`)}catch(e){throw new Error(`Импортировано ${completed} из ${rows.length}. ${e instanceof Error?e.message:'Ошибка импорта'}. Остальные занятия не изменены.`)}finally{await refresh()}})}/>}
 {tab==='grades'&&<StudyData section={data.snapshot.grades}/>}{tab==='umkd'&&<PlatonusUmkd section={data.snapshot.umkd}/>}
 {tab==='imports'&&<div className="space-y-3"><p className="text-xs text-muted-foreground">Последние 50 импортов. Полный журнал доступен в «Истории изменений» → «Журнал действий».</p>{!data.imports.length&&<p className="text-sm text-muted-foreground">Изменения ещё не применялись.</p>}{data.imports.map(item=>{const after=JSON.parse(item.after_json),source=JSON.parse(item.source_json);return <article key={item.id} className="flex flex-wrap items-center justify-between gap-3 rounded-lg border p-4"><div className="min-w-0"><p className="break-words font-medium">{source.subject}</p><p className="text-sm">{stamp(item.created_at)} · {item.before_json?'Обновлено':'Добавлено'} занятие · {days[after.weekday]} {after.start_time}</p><p className="text-xs text-muted-foreground">Источник: расписание Platonus · {after.lesson_type}</p></div><Button variant="outline" disabled={busy||Boolean(item.reverted_at)} onClick={()=>void run(async()=>{await requestApi(`/api/platonus/imports/${item.id}/revert`,{method:'POST'});await refresh()})}>{item.reverted_at?t("Отменено"):'Откатить'}</Button></article>})}</div>}</>}
 {initialTab==='schedule'&&<a className="inline-block text-sm text-primary underline" href="https://platonus.kstu.kz/" target="_blank" rel="noreferrer">Открыть Platonus</a>}
 </Container>
}
