import {t,useLanguage} from '../lib/language'
import {useState} from 'react'
import type {PlatonusLesson} from '../../bridge/platonus-parser'
import {Button} from './ui/button'
export type PreviewRow={index:number;lesson:PlatonusLesson;weekType:string;status:string;revision:string;existing:Record<string,unknown>|null;collisions:Record<string,unknown>[]}
const days=['','Понедельник','Вторник','Среда','Четверг','Пятница','Суббота','Воскресенье']
export function PlatonusSchedulePreview({rows,weeks,busy,onImport}:{rows:PreviewRow[];weeks:number[];busy:boolean;onImport:(rows:PreviewRow[])=>void}){
 useLanguage();
 const [week,setWeek]=useState(weeks[0]),[excluded,setExcluded]=useState<Set<number>>(new Set())
 const available=rows.filter(r=>['add','update'].includes(r.status)),selected=available.filter(r=>!excluded.has(r.index))
 const shown=weeks.includes(week)?week:weeks[0]
 return <section className="space-y-4" aria-label="Предпросмотр расписания Platonus">
 <div className="space-y-3 rounded-lg border bg-card p-4"><h2 className="font-semibold">Проверьте и импортируйте расписание</h2><p className="text-sm text-muted-foreground">1. Посмотрите обе недели. 2. Снимите галочки с ненужных изменений. 3. Нажмите «Импортировать». Занятия появятся в основном расписании до конца семестра.</p><p className="text-sm text-muted-foreground">Ваши дополнительные занятия сохранятся. Пересечения не импортируются. Любое применённое изменение можно откатить в истории импорта.</p><div className="flex flex-wrap items-center gap-3"><Button disabled={busy||!selected.length} onClick={()=>onImport(selected)}>{busy?'Импортируем…':`Импортировать выбранные (${selected.length})`}</Button><span className="text-sm text-muted-foreground">Новых: {available.filter(r=>r.status==='add').length} · Изменений: {available.filter(r=>r.status==='update').length} · Пересечений: {rows.filter(r=>r.status==='conflict').length}</span></div></div>
 <p className="text-xs text-muted-foreground">Номера недель считаются от начала семестра в Platonus: это не номера подгрупп. Здесь показаны два последовательных типа недели.</p><div className="flex flex-wrap gap-2" aria-label="Учебная неделя">{weeks.map(w=><Button key={w} variant={shown===w?'default':'outline'} aria-pressed={shown===w} onClick={()=>setWeek(w)}>{rows.find(r=>r.lesson.weekNumber===w)?.weekType==='odd'?t("Числитель"):rows.find(r=>r.lesson.weekNumber===w)?.weekType==='even'?t("Знаменатель"):`Неделя ${w}`} · №{w}</Button>)}</div>
 {!rows.length&&<p className="text-sm text-muted-foreground">На этих неделях занятия не найдены.</p>}
 <div className="grid items-start gap-3 sm:grid-cols-2 xl:grid-cols-3">{[1,2,3,4,5,6,7].filter(day=>day<6||rows.some(r=>r.lesson.weekNumber===shown&&r.lesson.weekday===day)).map(day=>{const list=rows.filter(r=>r.lesson.weekNumber===shown&&r.lesson.weekday===day).sort((a,b)=>a.lesson.startTime.localeCompare(b.lesson.startTime));return <section key={day} className="min-w-0 space-y-2"><h3 className="text-sm font-semibold">{days[day]}</h3>{!list.length&&<p className="rounded-lg border border-dashed p-4 text-sm text-muted-foreground">Нет занятий</p>}{list.map(row=><article key={row.index} className="min-w-0 space-y-2 rounded-lg border bg-card p-3"><div className="flex justify-between gap-2 text-xs text-muted-foreground"><span>{row.lesson.slotNumber}-я пара</span><span>{row.lesson.startTime}–{row.lesson.endTime}</span></div><h4 className="break-words text-sm font-medium">{row.lesson.subject}</h4><p className="text-xs text-muted-foreground">{row.lesson.lessonType}</p><p className="break-words text-sm">{row.lesson.teacher||'Преподаватель не указан'}</p><p className="break-words text-sm">{[row.lesson.building,row.lesson.room].filter(Boolean).join(' · ')||'Кабинет не указан'}</p>{['add','update'].includes(row.status)?<label className="flex cursor-pointer items-center gap-2 border-t pt-2 text-sm"><input type="checkbox" disabled={busy} checked={!excluded.has(row.index)} onChange={e=>setExcluded(old=>{const next=new Set(old);if(e.target.checked)next.delete(row.index);else next.add(row.index);return next})}/>{row.status==='add'?'Добавить занятие':'Обновить занятие'}</label>:<p className="border-t pt-2 text-xs text-muted-foreground">{row.status==='unchanged'?'Уже в расписании':'Пересечение — пропущено'}</p>}{row.status==='update'&&<details className="text-xs text-muted-foreground"><summary className="cursor-pointer">Что сейчас в Campus</summary><p className="break-words pt-1">{[row.existing?.teacher,row.existing?.lesson_type,row.existing?.building,row.existing?.room].filter(Boolean).join(' · ')}</p></details>}{row.status==='conflict'&&<p className="break-words text-xs text-amber-700 dark:text-amber-300">В это время: {row.collisions.map(c=>c.subject).join(', ')}. Разрешите пересечение в редакторе расписания.</p>}</article>)}</section>})}</div>
 </section>
}
