import {useEffect,useState,useRef} from 'react'
import {CheckCircle2,Clock3,RefreshCw} from 'lucide-react'
import {requestApi} from '../lib/api-client'
import {t,useLanguage} from '../lib/language'
import {Button} from './ui/button'
type State={status:string;needsCode:boolean;lastSyncAt:string|null;retryAt:number|null;initialImportDone:boolean;error:string|null;credentialsSaved:boolean}
export function PlatonusConnect({onReady}:{onReady?:()=>void}){
 useLanguage();const [state,setState]=useState<State|null>(null),[login,setLogin]=useState(''),[password,setPassword]=useState(''),[remember,setRemember]=useState(false),[code,setCode]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('')
 useEffect(()=>{let active=true;async function poll(){try{const value=await requestApi<State>('/api/platonus/connection');if(active)setState(value)}catch(e){if(active)setError((e as Error).message)}}void poll();const timer=setInterval(poll,4000);return()=>{active=false;clearInterval(timer)}},[])
 async function act(op:string,body:unknown={}){setBusy(true);setError('');try{setState(await requestApi<State>(`/api/platonus/${op}`,{method:'POST',body:JSON.stringify(body)}));setPassword('');setCode('')}catch(e){setError((e as Error).message)}finally{setPassword('');setBusy(false)}}
 const ready=state?.initialImportDone&&state.status==='connected'&&!state.retryAt,waiting=!!state?.retryAt,syncing=state?.status==='syncing'
 const advanced=useRef(false)
 useEffect(()=>{if(ready&&onReady&&!advanced.current){advanced.current=true;onReady()}},[ready,onReady])
 const formVisible=(!syncing&&!waiting&&ready&&!state?.credentialsSaved)||!state||(!waiting&&!syncing&&!ready&&(state.status==='disconnected'||state.status==='expired'||(state.status==='verification'&&!state.needsCode)||(!state.credentialsSaved&&state.status!=='verification')))
 return <section className="overflow-hidden rounded-2xl border bg-card"><div className={ready?"bg-[#b72835] px-6 py-4 text-white":"bg-[#b72835] px-6 py-7 text-white"}><div className="mb-5 flex items-center gap-3"><img src="/platonus-logo.png" alt="" className="h-12 w-auto rounded"/><span className="text-2xl font-semibold tracking-tight">Platonus</span></div>{!ready&&<h2 className="text-xl font-semibold">{t('Ваш университет — в одном месте')}</h2>}<p className="mt-2 max-w-xl text-sm leading-6 text-white/90">{t(ready?(state?.credentialsSaved?'Расписание, оценки и УМКД обновляются автоматически каждый час.':'Данные загружены. Для следующего обновления войдите в Platonus снова.'):'Введите данные своего аккаунта Platonus. Campus загрузит расписание, оценки и учебные материалы.')}</p><a className="mt-2 inline-block text-xs text-white/80 underline" href="https://platonus.kstu.kz/" target="_blank" rel="noreferrer">platonus.kstu.kz</a></div><div className="space-y-4 p-5 sm:p-6">
 {formVisible&&<form className="space-y-4" onSubmit={e=>{e.preventDefault();void act('login',{login,password,remember});if(!remember)setLogin('')}}><label className="block text-sm">{t('Логин')} Platonus<input required autoComplete="username" value={login} onChange={e=>setLogin(e.target.value)} className="mt-1 w-full rounded-lg border bg-background px-3 py-3"/></label><label className="block text-sm">{t('Пароль')} Platonus<input required type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} className="mt-1 w-full rounded-lg border bg-background px-3 py-3"/></label><label className="flex items-start gap-3 text-sm"><input type="checkbox" checked={remember} onChange={e=>setRemember(e.target.checked)} className="mt-1 size-4 shrink-0"/><span>{t("Запомнить данные входа")}<span className="mt-1 block text-xs text-muted-foreground">{t("С галочкой Campus сохраняет логин и пароль зашифрованными и обновляет данные автоматически. Без неё для каждого обновления нужно входить заново.")}</span></span></label><Button className="w-full bg-[#b72835] text-white hover:bg-[#98202c]" disabled={busy}>{busy?t('Подключаем университет…'):t('Подключить Platonus')}</Button></form>}
 {state?.needsCode&&<form className="space-y-3" onSubmit={e=>{e.preventDefault();void act('verify',{code})}}><label>{t('Код подтверждения')}<input required inputMode="numeric" autoComplete="one-time-code" value={code} onChange={e=>setCode(e.target.value)} className="mt-1 w-full rounded-lg border bg-background p-3"/></label><Button disabled={busy}>{t('Подтвердить')}</Button></form>}
 {waiting&&<div role="status" className="flex gap-3 rounded-lg bg-amber-500/10 p-4 text-sm"><Clock3 className="size-5 shrink-0"/><p>{t('Platonus временно недоступен. Campus повторит попытку через 5 минут — сайт можно закрыть.')}</p></div>}
 {state?.status==='connected'&&!waiting&&!syncing&&!ready&&<Button variant="outline" disabled={busy} onClick={()=>void act('sync')}>{t('Повторить')}</Button>}
 {syncing&&<p role="status" className="flex gap-2 text-sm"><RefreshCw className="size-4 animate-spin"/>{t('Готовим ваше расписание…')}</p>}
 {ready&&<div className="space-y-3"><p className="flex items-center gap-2 font-medium"><CheckCircle2 className="size-5 text-emerald-600"/>{t('Platonus подключён')}</p>{onReady&&<Button onClick={onReady}>{t('Начать работу')}</Button>}</div>}
 {(error||(!waiting&&state?.error))&&<p role="alert" className="text-sm text-destructive">{t(error||state?.error||'')}</p>}
 {(ready||waiting||syncing)&&<Button variant="ghost" size="sm" disabled={busy} onClick={()=>void act('disconnect')}>{t('Отключить Platonus')}</Button>}
 </div></section>
}
