import {useEffect,useState} from 'react'
import {Plus,Paperclip,Menu,FileText,Check} from 'lucide-react'
import {requestApi} from '../lib/api-client'
import {campusApi,dueAtForDate,formatDueDate,type AttachmentInfo,type ScheduleDayLesson} from '../lib/campus-api'
import {t,useLanguage} from '../lib/language'
import {toDateKey} from '../lib/schedule-date'
import {AttachmentList,ConfirmDelete,FilePicker,UploadStatus,addDaysKey,useUploads} from './lesson-files'
import {Button} from './ui/button'
import {Modal} from './ui/modal'
import {LoadingState} from './ui/page-state'
type Task={id:string;title:string;subjectId?:string;subjectName:string;scheduleSlotId?:string|null;description:string|null;dueAt:string|null;status:string;attachments?:AttachmentInfo[]}
type Upcoming=ScheduleDayLesson&{key:string}
let upcomingCache:Promise<Upcoming[]>|null=null
/** Ближайшие занятия на две недели вперёд — чтобы привязать задание к конкретной паре. */
function upcomingLessons(){
 const today=toDateKey(new Date())
 upcomingCache??=Promise.all(Array.from({length:15},(_,i)=>campusApi.scheduleDay(addDaysKey(today,i)).catch(()=>null))).then(days=>days.flatMap(day=>day?day.lessons.filter(l=>l.status!=='cancelled').map(l=>({...l,key:`${l.originalDate||day.date}__${l.scheduleSlotId}`})):[]))
 const current=upcomingCache;setTimeout(()=>{if(upcomingCache===current)upcomingCache=null},60_000)
 return current
}
const lessonLabel=(l:Upcoming)=>`${new Date(`${l.key.slice(0,10)}T12:00:00`).toLocaleDateString('ru-RU',{weekday:'short',day:'numeric',month:'short'})} · ${l.startTime}${l.lessonType?` · ${l.lessonType}`:''}`
export function TaskWorkspace({onMenuClick}:{onMenuClick:()=>void}){
 useLanguage()
 const [tasks,setTasks]=useState<Task[]>([]),[subjects,setSubjects]=useState<{id:string;name:string}[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[query,setQuery]=useState(''),[filter,setFilter]=useState('open'),[selected,setSelected]=useState<Task|null>(null),[creating,setCreating]=useState(false),[busy,setBusy]=useState(false),[files,setFiles]=useState<AttachmentInfo[]>([])
 const [subject,setSubject]=useState(''),[lessons,setLessons]=useState<Upcoming[]>([]),[lessonKey,setLessonKey]=useState(''),[due,setDue]=useState(''),[pending,setPending]=useState<File[]>([]),uploads=useUploads()
 const load=async()=>{const [rows,catalog]=await Promise.all([requestApi<Task[]>('/api/homework?limit=100'),requestApi<{subjects:{id:string;name:string}[]}>('/api/catalog')]);setTasks(rows);setSubjects(catalog.subjects)}
 useEffect(()=>{void load().catch(e=>setError(e.message)).finally(()=>setLoading(false))},[])
 useEffect(()=>{setFiles(selected?.attachments??[]);if(selected)void campusApi.attachments('homework',selected.id).then(setFiles).catch(e=>setError(e.message))},[selected?.id])
 const open=(task:Task|null)=>{setSelected(task);setCreating(!task);setError('');setPending([]);setSubject(task?.subjectId??'');setDue(task?.dueAt?.slice(0,10)??'');setLessonKey(task?.dueAt&&task.scheduleSlotId?`${task.dueAt.slice(0,10)}__${task.scheduleSlotId}`:'');void upcomingLessons().then(setLessons)}
 const subjectLessons=lessons.filter(l=>l.subjectId===subject)
 const visible=tasks.filter(task=>(filter==='all'||task.status===filter)&&`${task.title} ${task.subjectName}`.toLowerCase().includes(query.toLowerCase()))
 async function save(form:HTMLFormElement){const data=new FormData(form),slot=lessonKey?lessonKey.slice(12):null;setBusy(true);setError('');try{const value={title:String(data.get('title')).trim(),description:String(data.get('description')).trim()||null,dueAt:due?dueAtForDate(due):null,scheduleSlotId:slot,...(!selected?{subjectId:subject}:{})};const task=await requestApi<Task>(selected?`/api/homework/${selected.id}`:'/api/homework',{method:selected?'PATCH':'POST',body:JSON.stringify(value)});if(pending.length){await uploads.run('homework',task.id,pending);setPending([])}if(!selected){setCreating(false);setSelected(null)}else setSelected({...selected,...task});await load()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function upload(chosen:File[]){if(!selected)return;await uploads.run('homework',selected.id,chosen);setFiles(await campusApi.attachments('homework',selected.id).catch(()=>files))}
 const close=()=>{if(!busy&&!uploads.busy){setSelected(null);setCreating(false);void load().catch(()=>{})}}
 return <main className="mx-auto max-w-5xl space-y-5 p-4 sm:p-6"><header className="flex items-center gap-3"><Button variant="ghost" size="icon" className="md:hidden" onClick={onMenuClick} aria-label={t('Открыть меню')}><Menu/></Button><div className="flex-1"><h1 className="text-xl font-semibold">{t('Задания')}</h1><p className="text-sm text-muted-foreground">{t('Домашние задания и сроки по всем предметам')}</p></div><Button onClick={()=>open(null)}><Plus className="size-4"/>{t('Добавить')}</Button></header><p className="text-sm text-muted-foreground">{t('Добавьте задание здесь, в карточке занятия в расписании или напишите в AI: «ДЗ по математике: решить задачи 2–5 к среде». Фото и файлы можно прикрепить сразу.')}</p><div className="flex flex-wrap gap-2"><input aria-label={t('Поиск заданий')} placeholder={t('Предмет или задание')} value={query} onChange={e=>setQuery(e.target.value)} className="min-w-0 flex-1 rounded-md border bg-card p-2"/><select aria-label={t('Статус задания')} value={filter} onChange={e=>setFilter(e.target.value)} className="rounded-md border bg-card p-2"><option value="open">{t('К выполнению')}</option><option value="done">{t('Выполнено')}</option><option value="all">{t('Все')}</option></select></div>{error&&!selected&&!creating&&<p role="alert" className="text-sm text-destructive">{error}</p>}{loading?<LoadingState/>:visible.length?<div className="divide-y rounded-xl border bg-card">{visible.map(task=><button key={task.id} className="flex w-full items-start gap-3 p-4 text-left hover:bg-muted/40" onClick={()=>open(task)}><span className="mt-1 rounded-md bg-primary/10 p-2">{task.status==='done'?<Check className="size-4"/>:<FileText className="size-4"/>}</span><span className="min-w-0 flex-1"><span className="block text-xs text-muted-foreground">{task.subjectName}</span><strong className="mt-1 block break-words text-sm">{task.title}</strong>{task.description&&<span className="mt-1 line-clamp-2 block text-sm text-muted-foreground">{task.description}</span>}<span className="mt-2 flex flex-wrap gap-x-3 text-xs">{task.dueAt&&<span>{t('До')} {formatDueDate(task.dueAt)}{task.scheduleSlotId?` · ${t('к паре')}`:''}</span>}{!!task.attachments?.length&&<span className="inline-flex items-center gap-1 text-muted-foreground"><Paperclip className="size-3"/>{task.attachments.length}</span>}</span></span></button>)}</div>:<p className="rounded-xl border border-dashed p-8 text-center text-sm text-muted-foreground">{t('Заданий с такими условиями пока нет.')}</p>}{tasks.length===100&&<p className="text-xs text-muted-foreground">{t('Показаны последние 100 заданий.')}</p>}
 {(selected||creating)&&<Modal title={selected?t('Задание'):t('Новое задание')} onClose={close}><form key={selected?.id??'new'} onSubmit={e=>{e.preventDefault();void save(e.currentTarget)}} className="space-y-4 p-4">
  <label className="block text-sm">{t('Предмет')}{selected?<span className="mt-1 block font-medium">{selected.subjectName||subjects.find(s=>s.id===selected.subjectId)?.name}</span>:<select required value={subject} onChange={e=>{setSubject(e.target.value);setLessonKey('')}} className="mt-1 w-full rounded-md border bg-card p-2"><option value="">{t('Выберите предмет')}</option>{subjects.map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select>}</label>
  <label className="block text-sm">{t('Что сделать')}<input required name="title" maxLength={300} defaultValue={selected?.title} className="mt-1 w-full rounded-md border bg-card p-2"/></label>
  <label className="block text-sm">{t('Подробности')}<textarea name="description" maxLength={10000} defaultValue={selected?.description??''} rows={4} className="mt-1 w-full rounded-md border bg-card p-2"/></label>
  {subject&&<label className="block text-sm">{t('К какому занятию')}<select value={lessonKey} onChange={e=>{setLessonKey(e.target.value);if(e.target.value)setDue(e.target.value.slice(0,10))}} className="mt-1 w-full rounded-md border bg-card p-2"><option value="">{t('Без привязки к паре — только срок')}</option>{lessonKey&&!subjectLessons.some(l=>l.key===lessonKey)&&<option value={lessonKey}>{formatDueDate(lessonKey)} · {t('текущая пара')}</option>}{subjectLessons.map(l=><option key={l.key} value={l.key}>{lessonLabel(l)}</option>)}</select>{!subjectLessons.length&&<span className="mt-1 block text-xs text-muted-foreground">{lessons.length?t('В ближайшие две недели пар по этому предмету нет — укажите срок.'):t('Загружаем ближайшие занятия…')}</span>}</label>}
  <label className="block text-sm">{t('Срок')}<input type="date" value={due} onChange={e=>{const value=e.target.value;setDue(value);if(lessonKey)setLessonKey(subjectLessons.find(l=>l.key===`${value}__${lessonKey.slice(12)}`)?.key??'')}} className="mt-1 w-full rounded-md border bg-card p-2"/></label>
  {!selected&&<><FilePicker disabled={busy} onFiles={chosen=>setPending(list=>[...list,...chosen])} label={t('Фото, PDF или документ к заданию')}/>{pending.length>0&&<p className="text-xs text-muted-foreground">{t('Будет прикреплено:')} {pending.map(f=>f.name).join(', ')} <button type="button" className="text-primary underline" onClick={()=>setPending([])}>{t('Очистить')}</button></p>}</>}
  <UploadStatus items={uploads.items} onDismiss={uploads.dismiss}/>
  {error&&<p role="alert" className="text-sm text-destructive">{error}</p>}
  <div className="flex flex-wrap items-center gap-2"><Button type="submit" disabled={busy||(!selected&&!subject)}>{busy?t('Сохранение…'):t('Сохранить')}</Button>{selected&&<Button type="button" variant="outline" disabled={busy} onClick={()=>{setBusy(true);void requestApi(`/api/homework/${selected.id}`,{method:'PATCH',body:JSON.stringify({status:selected.status==='done'?'open':'done'})}).then(()=>{setSelected(null);return load()}).catch(e=>setError(e.message)).finally(()=>setBusy(false))}}>{selected.status==='done'?t('Вернуть в работу'):t('Выполнено')}</Button>}{selected&&<span className="ml-auto"><ConfirmDelete label={t('Удалить задание')} onConfirm={()=>campusApi.deleteHomework(selected.id).then(()=>{setSelected(null);return load()}).catch(e=>setError(e.message))}/></span>}</div>
 </form>{selected&&<section className="space-y-3 border-t p-4"><h3 className="flex items-center gap-2 text-sm font-semibold"><Paperclip className="size-4"/>{t('Файлы и изображения')}</h3><AttachmentList files={files} onDelete={file=>campusApi.deleteAttachment(file.id).then(()=>setFiles(list=>list.filter(f=>f.id!==file.id))).catch(e=>setError(e.message))}/><FilePicker disabled={uploads.busy} onFiles={chosen=>void upload(chosen)}/><p className="text-xs text-muted-foreground">{t('PDF, Word, Excel, презентации и изображения (включая HEIC) · до 20 МБ на файл')}</p></section>}</Modal>}
 </main>
}
