import {t,useLanguage} from '../lib/language'
import { useEffect, useState } from 'react'
import { RefreshCw } from 'lucide-react'
import { requestApi } from '../lib/api-client'
import { Button } from './ui/button'
import { LoadingState, ErrorState } from './ui/page-state'
type Usage={processingErrors:{error:string;createdAt:string}[];model:string;workspaceBytes:number|null;workspaceLimitBytes:number;dailyRequestLimit:number;quotaReset:string;today:{requests:number;failures:number;inputTokens:number|null;outputTokens:number|null};recent:{purpose:string;status:string;error:string|null;durationMs:number|null;createdAt:string}[]}
const locales={ru:'ru-RU',en:'en-GB',kk:'kk-KZ'} as const
function Meter({value,max,label}:{value:number;max:number;label:string}){const share=max>0?Math.min(100,value/max*100):0;return <div role="progressbar" aria-label={label} aria-valuemin={0} aria-valuemax={max} aria-valuenow={value} className="mt-3 h-2 overflow-hidden rounded-full bg-muted"><div className={share>=90?'h-full rounded-full bg-destructive':share>=70?'h-full rounded-full bg-amber-500':'h-full rounded-full bg-primary'} style={{width:`${Math.max(share,value>0?2:0)}%`}}/></div>}
export function UsageSettings(){
 const language=useLanguage(),locale=locales[language as keyof typeof locales]??'ru-RU',when=(value:string)=>{const d=new Date(value);return Number.isNaN(d.getTime())?value:d.toLocaleString(locale,{day:'numeric',month:'long',hour:'2-digit',minute:'2-digit'})}
 const [data,setData]=useState<Usage|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false)
 async function load(){setBusy(true);try{setData(await requestApi<Usage>('/api/usage'));setError('')}catch(e){setError(e instanceof Error?e.message:t('Нет связи'))}finally{setBusy(false)}}
 useEffect(()=>{void load();const timer=setInterval(()=>void load(),30000);return()=>clearInterval(timer)},[])
 const mb=(bytes:number)=>bytes>=1024**3?`${(bytes/1024**3).toFixed(bytes%1024**3?1:0)} ${t('ГБ')}`:`${(bytes/1024**2).toFixed(1)} ${t('МБ')}`
 return <section className="space-y-4"><div className="flex items-center justify-between gap-3"><h2 className="text-base font-semibold">{t("AI и лимиты")}</h2><Button variant="outline" disabled={busy} onClick={()=>void load()}><RefreshCw className={busy?'size-4 animate-spin':'size-4'}/>{t("Обновить")}</Button></div>{error&&<ErrorState message={error} onRetry={data?undefined:()=>void load()}/>}{!data&&!error&&<LoadingState/>}{data&&<>
  <div className="grid gap-3 sm:grid-cols-2"><div className="rounded-lg border bg-card p-4"><p className="text-sm text-muted-foreground">{t('Запросы к AI сегодня')}</p><p className="mt-1 text-2xl font-semibold tabular-nums">{data.today.requests}<span className="text-base font-normal text-muted-foreground"> / {data.dailyRequestLimit}</span></p><Meter value={data.today.requests} max={data.dailyRequestLimit} label={t('Использованные запросы AI')}/><p className="mt-2 text-xs text-muted-foreground">{t('Общий лимит для чата и разбора сообщений. Обновится {time}.').replace('{time}',when(data.quotaReset))}</p>{data.today.failures>0&&<p className="mt-2 text-xs text-destructive">{t('Ошибок сегодня: {n}').replace('{n}',String(data.today.failures))}</p>}</div>
  <div className="rounded-lg border bg-card p-4"><p className="text-sm text-muted-foreground">{t('Хранилище')}</p><p className="mt-1 text-2xl font-semibold tabular-nums">{data.workspaceBytes===null?'—':mb(data.workspaceBytes)}<span className="text-base font-normal text-muted-foreground"> / {mb(data.workspaceLimitBytes)}</span></p>{data.workspaceBytes!==null&&<Meter value={data.workspaceBytes} max={data.workspaceLimitBytes} label={t('Занятое хранилище')}/>}<p className="mt-2 text-xs text-muted-foreground">{t('Расписание, история и файлы вашего аккаунта. Один файл — до 20 МБ.')}</p></div></div>
  <details className="rounded-lg border bg-card p-4 text-xs text-muted-foreground"><summary className="cursor-pointer text-sm font-medium text-foreground">{t('Технические подробности')}</summary><p className="mt-3 break-all">{t('Модель')}: {data.model}</p><p className="mt-1">{t('Токены сегодня: вход {in}, выход {out}.').replace('{in}',String(data.today.inputTokens??'—')).replace('{out}',String(data.today.outputTokens??'—'))}</p><p className="mt-2">Остаток общей квоты Workers AI и расход оперативной памяти Cloudflare не передаёт этому приложению. Они не равны лимиту запросов выше. Общие показатели доступны владельцу хостинга в <a className="underline" href="https://dash.cloudflare.com/" target="_blank" rel="noreferrer">панели Cloudflare</a>.</p></details>
  <h3 className="text-sm font-semibold">{t('Ошибки обработки')}</h3>{data.processingErrors.length===0?<p className="text-sm text-muted-foreground">{t('Ошибок обработки не зафиксировано.')}</p>:data.processingErrors.map((r,i)=><div key={i} className="rounded-lg border border-destructive/40 p-3 text-sm"><time className="text-xs text-muted-foreground">{when(r.createdAt)}</time><p className="mt-1 whitespace-pre-wrap break-words text-destructive">{r.error}</p></div>)}<h3 className="text-sm font-semibold">{t('Последние обращения к AI')}</h3>{!data.recent.length&&<p className="text-sm text-muted-foreground">{t('Обращений пока нет.')}</p>}<ul className="space-y-2">{data.recent.map((r,i)=><li key={`${r.createdAt}-${i}`} className="rounded-lg border p-3 text-sm"><p>{r.purpose==='assistant'?t('Чат'):t("Сообщения")} · <span className={r.status==='failed'?'text-destructive':undefined}>{r.status==='completed'?t('Успешно'):r.status==='failed'?t('Сбой'):t('Выполняется')}</span>{r.durationMs!==null?` · ${t('{n} с').replace('{n}',(r.durationMs/1000).toFixed(1))}`:''}</p><time className="text-xs text-muted-foreground">{when(r.createdAt)}</time>{r.error&&<p className="mt-1 break-words text-destructive">{r.error}</p>}</li>)}</ul></>}</section>
}
