import {useFeature} from '../lib/features'
import {useAccount} from './auth-gate'
import {lazy,useEffect,useRef,useState} from 'react'
import {X,Pause,Play,RotateCcw,CalendarDays,MapPin,Pencil,Plus,BookOpen,CheckSquare2} from 'lucide-react'
import {Button} from './ui/button'
import type {AppPage} from './app-sidebar'
import {t,useLanguage,LanguageSelect} from '../lib/language'
import type {Turn} from './assistant-page'
const AssistantPage=lazy(()=>import('./assistant-page').then(m=>({default:m.AssistantPage})))
import {tutorialMessages,tutorialPhase,tutorialSchedule} from '../lib/tutorial'
import {TourCoachmark} from './tour-coachmark'
import {DemoTeacherProfile} from './demo-teacher-profile'
const titles=['День и неделя','Редактирование вручную','Сколько осталось до конца пары','Карточка преподавателя','Спросите AI','Отмена пары','Добавление занятия','Домашнее задание','Откат изменений','Ваши учебные материалы']
const hints=[
 'Переключите день и неделю. В учебном примере выбрана среда; настоящие занятия не меняются.',
 'Нажмите «Редактировать», измените кабинет и сохраните. В обычном расписании так же можно добавлять пары в свободные ячейки.',
 'Синяя рамка отмечает текущую пару. Шкала показывает, сколько прошло и сколько осталось. Сейчас время ускорено для демонстрации.',
 'Нажмите подсвеченное имя. Это вымышленный преподаватель: откройте его карточку и посмотрите, как устроены фото и информация.',
 'Посмотрите, как сообщение вводится в чат и появляется ответ. Это заранее подготовленный учебный диалог.',
 'Сначала AI найдёт первую пару среды, затем вы увидите, как она становится отменённой.',
 'Укажите день, номер пары, предмет и кабинет. Если время пары уже известно, его не нужно вводить заново.',
 'Задание появляется у нужного предмета. Для точного результата указывайте предмет и срок.',
 'Три учебных изменения отменяются: задание исчезнет, добавленная пара уберётся, физика восстановится.',
 'В УМКД можно открывать файлы по предметам, отмечать избранное и обновлять материалы. Обучение завершено — ваше настоящее расписание осталось прежним.',
]
export function WelcomeTour({navigate,onClose,onComplete,section='all'}:{navigate:(page:AppPage)=>void;onClose:()=>void;onComplete?:()=>void;section?:'all'|'schedule'|'assistant'|'library'}){
 const admin=useAccount()?.user.isAdmin,aiEnabled=useFeature('ai')
 const steps=section==='all'?[0,1,2,3,9]:(!aiEnabled&&section!=='library')?[0,1,2,3,...(section==='schedule'?[]:[9])]:section==='schedule'?[0,1,2,3]:section==='assistant'?[4,5,6,8]:section==='library'?[9]:[0,1,2,3,4,5,6,...(admin?[7]:[]),8,9]
 const lastStep=steps.at(-1),firstStep=steps[0]
 const language=useLanguage(),[step,setStep]=useState(firstStep),[elapsed,setElapsed]=useState(0),[paused,setPaused]=useState(false),[run,setRun]=useState(0)
 const [view,setView]=useState<'day'|'week'>('day'),[editing,setEditing]=useState(false),[room,setRoom]=useState('101'),[savedRoom,setSavedRoom]=useState('101'),[adding,setAdding]=useState(false),[manualLesson,setManualLesson]=useState<{name:string;room:string}|null>(null),[newSubject,setNewSubject]=useState('Математика'),[newRoom,setNewRoom]=useState('420')
 const [teacherOpen,setTeacherOpen]=useState(false),[favorite,setFavorite]=useState(false)
 const [reduced,setReduced]=useState(()=>matchMedia('(prefers-reduced-motion: reduce)').matches)
 const panel=useRef<HTMLElement>(null)
 useEffect(()=>{const media=matchMedia('(prefers-reduced-motion: reduce)'),update=()=>setReduced(media.matches);media.addEventListener('change',update);return()=>media.removeEventListener('change',update)},[])
 useEffect(()=>{setElapsed(0);setPaused(false);setEditing(false);setRoom('101');setSavedRoom('101');setView('day');setAdding(false);setManualLesson(null);setNewSubject(t('Математика'));panel.current?.focus({preventScroll:true})},[step,run,language])
 const messages=tutorialMessages.map(([text,reply],i)=>!admin&&i===0?[text,'Я помогу с расписанием. Укажите предмет, день и номер пары. Например: «Отмени первую пару в среду». Если занятие неясно, я уточню.']:!admin&&i===4?['Отмени последние 2 изменения','Отменяю добавление математики и отмену физики. Исходное расписание восстановлено.']:[text,reply])
 const messageIndex=step>=4&&step<=8?step-4:-1
 const message=messageIndex>=0?t(messages[messageIndex][0]):''
 const phase=tutorialPhase(step,elapsed,message.length,reduced)
 const finished=messageIndex>=0?phase.done:step===2?elapsed>=5000:true
 useEffect(()=>{if(paused||(messageIndex<0&&step!==2)||(messageIndex>=0&&phase.done))return;let last=performance.now();const timer=setInterval(()=>{const now=performance.now();if(!document.hidden)setElapsed(n=>n+Math.min(250,now-last));last=now},50);return()=>clearInterval(timer)},[paused,step,run,messageIndex,phase.done])
 useEffect(()=>{const visibility=()=>{if(document.hidden)setPaused(true)};document.addEventListener('visibilitychange',visibility);return()=>document.removeEventListener('visibilitychange',visibility)},[])
 const page:AppPage=step===9?'library':messageIndex>=0&&!phase.showSchedule?'assistant':'schedule'
 useEffect(()=>{navigate(page)},[page])
 const state=tutorialSchedule(step,phase.applied);if(!admin)state.homework=false
 const turns:Turn[]=messageIndex<0?[]:messages.slice(0,messageIndex+(phase.sent?1:0)).filter((_,i)=>admin||i!==3).map(([text,reply],i)=>({id:`tutorial-${i}`,createdAt:'',text:t(text),reply:i<messageIndex||phase.replied?t(reply):null,state:'demo',actionId:null,actionStatus:null}))
 const preview={turns,draft:typeof phase.draft==='number'?message.slice(0,phase.draft):'',thinking:phase.sent&&!phase.replied}
 const progress=(35+elapsed/200)%105,live=step===2
 const target=step===0?'[data-tour=modes]':step===1?(editing?'form input':'[data-tour=edit]'):step===2?'[data-tour=live-timer]':step===3?'[data-tour=teacher]':step===9?'[data-tour=library]':page==='assistant'?(phase.sent?'[role=log] article:last-child':'#assistant-input'):step===5?'[data-demo-lesson=physics]':step===6?'[data-demo-slot=third]':step===7?'[data-demo-homework-zone]':'[data-demo-undo-summary]'
 return <div className="mx-auto max-w-5xl pb-[50dvh] sm:pb-6">
 <TourCoachmark target={target} step={step}><aside ref={panel} tabIndex={-1} aria-label={t('Знакомство с Campus')} className="space-y-3">
 <header className="flex items-center gap-2"><span className="flex-1 text-xs font-medium text-muted-foreground">{t('Знакомство с Campus')} · {steps.indexOf(step)+1}/{steps.length}</span><LanguageSelect/><Button size="icon" variant="ghost" aria-label={t('Закрыть')} onClick={onClose}><X/></Button></header>
 <div><h2 className="font-semibold">{t(titles[step])}</h2><p className="mt-1 text-sm leading-relaxed text-muted-foreground">{t(step===8&&!admin?'Два учебных изменения отменяются: добавленная пара уберётся, физика восстановится.':hints[step])}</p></div>
 <footer className="flex flex-wrap items-center gap-2"><Button variant="ghost" size="sm" onClick={()=>step!==firstStep?(setElapsed(0),setStep(steps[steps.indexOf(step)-1])):onClose()}>{t(step!==firstStep?'Назад':'Пропустить')}</Button><Button size="icon" variant="ghost" title={t('Повторить шаг')} aria-label={t('Повторить шаг')} onClick={()=>setRun(n=>n+1)}><RotateCcw className="size-4"/></Button>{(!finished||step===2)&&<Button size="icon" variant="ghost" aria-label={t(paused?'Продолжить':'Пауза')} onClick={()=>setPaused(v=>!v)}>{paused?<Play className="size-4"/>:<Pause className="size-4"/>}</Button>}<span className="flex-1"/><Button size="sm" disabled={!finished} onClick={()=>step===lastStep?(onComplete?.(),onClose()):(setElapsed(0),setStep(steps[steps.indexOf(step)+1]))}>{t(step===lastStep?'Завершить':'Далее')}</Button></footer>
 <p className="text-[11px] text-muted-foreground">{t('Учебный пример — ваше расписание не изменяется')}</p>
 </aside></TourCoachmark>{teacherOpen&&<DemoTeacherProfile onClose={()=>setTeacherOpen(false)}/>}
 {page==='assistant'?<AssistantPage demoMode demo={preview} onMenuClick={()=>{}} onRefresh={()=>{}}/>:page==='library'?<main className="space-y-4 p-4 sm:p-6"><h1 className="text-xl font-semibold">{t('УМКД')}</h1><article data-tour="library" className="rounded-xl border p-4"><div className="flex items-center gap-3"><BookOpen className="size-6 text-primary"/><strong className="flex-1">{t('Математика')}</strong><Button variant="ghost" aria-pressed={favorite} onClick={()=>setFavorite(v=>!v)}>{t(favorite?'В избранном':'В избранное')}</Button></div><p className="mt-3 text-sm text-muted-foreground">{t('Силлабус · лекции · задания')}</p></article></main>:<main className="space-y-4 p-4 sm:p-6"><header className="flex flex-wrap items-center gap-3"><CalendarDays className="size-5 text-primary"/><h1 className="flex-1 text-xl font-semibold">{t('Расписание')}</h1><Button data-tour="edit" size="sm" variant={editing?'default':'outline'} onClick={()=>setEditing(v=>!v)}><Pencil className="size-4"/>{t('Редактировать')}</Button></header>
 <div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-medium">{t('Среда')}</h2><p className="text-xs text-muted-foreground">{t('Числитель · учебная неделя')}</p></div><div data-tour="modes" className={`flex rounded-lg border p-1 ${step===0?'ring-2 ring-primary/40':''}`}>{(['day','week'] as const).map(mode=><Button size="sm" key={mode} variant={mode===view?'default':'ghost'} aria-pressed={mode===view} onClick={()=>setView(mode)}>{t(mode==='day'?'День':'Неделя')}</Button>)}</div></div>
 {view==='week'&&<div className="grid grid-cols-5 gap-1 text-center text-xs text-muted-foreground">{['Пн','Вт','Ср','Чт','Пт'].map(day=><span key={day} className={`rounded-md p-2 ${day==='Ср'?'bg-primary/10 font-semibold text-primary':''}`}>{t(day)}</span>)}</div>}
 <div className={view==='week'?'grid grid-cols-[1fr_minmax(0,3fr)_1fr] gap-2':''}><div data-demo-schedule-changes className={view==='week'?'col-start-2 space-y-3':'space-y-3'}>
 {step===8&&<div data-demo-undo-summary className={`rounded-xl border p-3 text-sm motion-safe:transition-all motion-safe:duration-700 ${phase.applied?'border-emerald-400 bg-emerald-50 text-emerald-800 dark:bg-emerald-950/40 dark:text-emerald-200':'border-amber-400 bg-amber-50 text-amber-800 dark:bg-amber-950/40 dark:text-amber-200'}`}>{phase.applied?t(admin?'Все 3 изменения отменены. Исходное расписание восстановлено.':'Все 2 изменения отменены. Исходное расписание восстановлено.'):t(admin?'Сейчас будут отменены 3 изменения: отмена физики, новая пара и домашнее задание.':'Сейчас будут отменены 2 изменения: отмена физики и новая пара.')}</div>}
 <article data-demo-lesson="physics" data-cancelled={state.cancelled} className={`relative overflow-hidden rounded-xl border p-4 motion-safe:transition-all motion-safe:duration-1000 ${state.cancelled?'border-red-400 bg-red-50 dark:bg-red-950/40':live?'border-blue-500 ring-1 ring-blue-500':'bg-card'}`}>
 <div className="flex flex-wrap justify-between gap-2 text-xs text-muted-foreground"><span>1 · 09:00–10:45</span>{state.cancelled&&<strong className="text-red-700 dark:text-red-300">{t('Отменено')}</strong>}{live&&<span className="text-blue-600 dark:text-blue-300">{t('Сейчас')}</span>}</div><h3 className={`mt-2 font-semibold ${state.cancelled?'text-red-700 line-through dark:text-red-300':''}`}>{t('Физика')}</h3><p className="mt-1 text-xs text-muted-foreground">{t('Лекция')}</p><div className={`mt-2 text-sm ${step===3?'rounded border border-primary p-2':''}`}><button data-tour="teacher" className="text-left text-primary underline decoration-dotted underline-offset-4" onClick={()=>setTeacherOpen(true)}>{t('Александр Сергеевич Примеров')}</button></div><p className="mt-2 flex items-center gap-1 text-sm"><MapPin className="size-4"/>{savedRoom}</p>
 {editing&&!adding&&<form className="mt-4 space-y-3 border-t pt-3" onSubmit={e=>{e.preventDefault();setSavedRoom(room);setEditing(false)}}><label className="block text-sm">{t('Кабинет')}<input className="mt-1 w-full rounded-md border bg-background p-2" value={room} onChange={e=>setRoom(e.target.value)} maxLength={40}/></label><Button size="sm" type="submit">{t('Сохранить')}</Button></form>}
 {live&&<div data-tour="live-timer" className="mt-4 space-y-2 rounded-lg bg-blue-50 p-3 dark:bg-blue-950/40"><p className={`text-sm font-semibold ${progress>=50&&progress<55?'text-amber-700 dark:text-amber-200':'text-blue-700 dark:text-blue-200'}`}>{progress<50?t('До перемены'):progress<55?t('Перемена · продолжим через'):t('Вторая половина пары · осталось')} {Math.ceil(progress<50?50-progress:progress<55?55-progress:105-progress)} {t('мин')}</p><p className="text-xs tabular-nums">{t('Прошло')}: {Math.floor(progress)} {t('мин')} · {t('Осталось')}: {Math.ceil(105-progress)} {t('мин')}</p><div role="progressbar" aria-label={t('Текущая пара')} aria-valuemin={0} aria-valuemax={105} aria-valuenow={progress} className="h-1.5 overflow-hidden rounded-full bg-blue-500/15"><div className="h-full rounded-full bg-blue-500 motion-safe:transition-[width] motion-safe:duration-150 motion-safe:ease-linear" style={{width:`${progress/105*100}%`}}/></div></div>}
 </article><article className="rounded-xl border bg-card p-4"><p className="text-xs text-muted-foreground">2 · 10:55–12:40</p><h3 className="mt-2 font-semibold">{t('Английский язык')}</h3><p className="mt-1 text-xs text-muted-foreground">{t('Семинар')} · 202</p></article>
 <div data-demo-slot="third" className="overflow-hidden rounded-xl motion-safe:transition-all motion-safe:duration-1000">{state.added||manualLesson?<article data-demo-added="true" className="rounded-xl border border-blue-300 bg-blue-50 p-4 dark:border-blue-800 dark:bg-blue-950/30"><p className="text-xs text-muted-foreground">3 · 13:10–14:55</p><h3 className="mt-2 font-semibold">{manualLesson?.name||t('Математика')}</h3><p className="mt-1 text-xs text-muted-foreground">{t('Семинар')} · {manualLesson?.room||'420'}</p>{admin&&<div data-demo-homework-zone className={`mt-3 rounded-md p-2 text-sm motion-safe:transition-colors motion-safe:duration-700 ${state.homework?'bg-background':'border border-dashed text-muted-foreground'}`}>{state.homework?<p data-demo-homework className="flex items-center gap-2"><CheckSquare2 className="size-4"/>{t('Задачи 2–5 к среде')}</p>:t('Домашних заданий пока нет')}</div>}</article>:<div className="rounded-xl border border-dashed p-4 text-sm text-muted-foreground"><p>3 · 13:10–14:55</p><p className="mt-2">{t('Свободная пара')}</p></div>}</div>
 {editing&&!manualLesson&&<Button variant="outline" className="w-full border-dashed" onClick={()=>setAdding(true)}><Plus className="size-4"/>{t('Добавить пару')} · 3</Button>}
 {editing&&adding&&<form className="space-y-3 rounded-xl border border-primary p-4" onSubmit={e=>{e.preventDefault();setManualLesson({name:newSubject.trim(),room:newRoom.trim()});setAdding(false);setEditing(false)}}><p className="text-sm">3 · 13:10–14:55 · {t('Семинар')}</p><label className="block text-sm">{t('Предмет')}<input required className="mt-1 w-full rounded-md border bg-background p-2" value={newSubject} onChange={e=>setNewSubject(e.target.value)} maxLength={100}/></label><label className="block text-sm">{t('Кабинет')}<input required className="mt-1 w-full rounded-md border bg-background p-2" value={newRoom} onChange={e=>setNewRoom(e.target.value)} maxLength={40}/></label><Button size="sm" type="submit">{t('Добавить')}</Button></form>}
 </div></div></main>}
 </div>
}
